### ISSUE TITLE
Alphakill / Flip control sample issue

### ISSUE THREAD

**Issue by dbz400** [RPCS3/rpcs3#343]
It is being broken since https://github.com/DHrpcs3/rpcs3/commit/f8e8e2f624199adf5e994f1b20deab9b0ee05923

-Alphakill 
[E : RSXThread]: Failed to compile shader: 0(16) : error C0000: syntax error, unexpected '.', expecting "::" at token "."

![2](https://cloud.githubusercontent.com/assets/3000282/3282034/86d57a4a-f4d2-11e3-809f-da552d9d8b95.jpg)

-Flip control
![1](https://cloud.githubusercontent.com/assets/3000282/3282031/7190e2c8-f4d2-11e3-9cc7-ec60a3788528.jpg)

Last working build 

-Alphakill
![3](https://cloud.githubusercontent.com/assets/3000282/3282043/eacbaefc-f4d2-11e3-93c0-4e88c32f63c7.jpg)

-Flip control
![4](https://cloud.githubusercontent.com/assets/3000282/3282044/ed37c572-f4d2-11e3-8073-a0c0ac6b9ddc.jpg)
