### PR TITLE
MacOs: Hopefully fixes build

### PR DESCRIPTION
**Pull request by elad335**
Simplify narrow function.
Fixes signed vs unsigned comparison error.

### CODE REVIEW

**Comment by elad335** [comment]
Seems like MacOs ARM64 build got stuck without compilation error but MacOs x86 built fine. Merging.

**Comment by riverwander** [comment]
Not sure why but this update seems like it broke rpcs3 for Linux x86. All games crash right after spu cache finishes building. Rolled back one update to fix.

**Comment by elad335** [comment]
@riverwander It seems you are describing a cross-platform issue though I can't reproduce it. Can you open an issue?

**Comment by schm1dtmac** [comment]
> Seems like MacOs ARM64 build got stuck without compilation error but MacOs x86 built fine. Merging.

Yeah I’ve filed that one at #17746, seems to have been caused by PR #17725.
