### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by KaaPex** [RPCS3/rpcs3#4090]
On Mac OS: 
rpcs3/rpcs3qt/gs_frame.cpp:171:25: error: use of undeclared identifier 'XOpenDisplay'
                return std::make_pair(XOpenDisplay(0), (unsigned long)(this->winId()));

xquartz is installed, where i should set /usr/X11/include?

**Comment by Asinin3** [comment]
Mac isn't supported because it doesn't work with OpenGL 4.3

**Comment by KaaPex** [comment]
OK
