### ISSUE TITLE
Build is broken with clang & libcxx version 22

### ISSUE THREAD

**Issue by v-fox** [RPCS3/rpcs3#18306]
### Quick summary

Doesn't build after update from clang & libcxx 21 to 22, workaround of `-stdlib=libstdc++` doesn't work because it isn't compatible with linking to non-libstdc++ dependencies, like Qt, if whole system is using libcxx by default.

### Details

Seems to have something to do with [recent changes to libcxx](https://github.com/llvm/llvm-project/issues/179319). Proposed workarounds, such as `-D_GLIBCXX_USE_CXX11_ABI=0 -D_LIBCPP_DISABLE_NEW_DELETE_DEFINITIONS`, did not work.

### Attach a log file

Fails with:
```
In file included from ../rpcs3-9999/rpcs3/Emu/NP/np_notifications.cpp:1:
In file included from ../rpcs3-9999/rpcs3/stdafx.h:6:
In file included from ../rpcs3-9999/Utilities/Config.h:5:
In file included from ../rpcs3-9999/rpcs3/util/logs.hpp:3:
In file included from /usr/include/c++/v1/map:602:
In file included from /usr/include/c++/v1/__tree:42:
/usr/include/c++/v1/__utility/lazy_synth_three_way_comparator.h:43:54: error: no matching function for call to object of type 'const std::less<void>'
   43 |   _LIBCPP_HIDE_FROM_ABI bool __less() const { return __comp_(__lhs_, __rhs_); }
      |                                                      ^~~~~~~
/usr/include/c++/v1/__tree:1818:20: note: in instantiation of member function 'std::__lazy_compare_result<std::less<void>, SceNpRoomId, SceNpRoomId>::__less' requested here
 1818 |     if (__comp_res.__less()) {
      |                    ^
/usr/include/c++/v1/__tree:1331:39: note: in instantiation of function template specialization 'std::__tree<std::__value_type<SceNpRoomId, unsigned int>, std::__map_value_compare<SceNpRoomId, std::pair<const SceNpRoomId, unsigned int>, std::less<SceNpRoomId>>, std::allocator<std::pair<const SceNpRoomId, unsigned int>>>::__find_equal<SceNpRoomId>' requested here
 1331 |     return const_cast<__tree*>(this)->__find_equal(__v);
      |                                       ^
/usr/include/c++/v1/__tree:1217:26: note: in instantiation of function template specialization 'std::__tree<std::__value_type<SceNpRoomId, unsigned int>, std::__map_value_compare<SceNpRoomId, std::pair<const SceNpRoomId, unsigned int>, std::less<SceNpRoomId>>, std::allocator<std::pair<const SceNpRoomId, unsigned int>>>::__find_equal<SceNpRoomId>' requested here
 1217 |     auto [__, __match] = __find_equal(__key);
      |                          ^
/usr/include/c++/v1/map:1314:107: note: in instantiation of function template specialization 'std::__tree<std::__value_type<SceNpRoomId, unsigned int>, std::__map_value_compare<SceNpRoomId, std::pair<const SceNpRoomId, unsigned int>, std::less<SceNpRoomId>>, std::allocator<std::pair<const SceNpRoomId, unsigned int>>>::find<SceNpRoomId>' requested here
 1314 |   [[__nodiscard__]] _LIBCPP_HIDE_FROM_ABI const_iterator find(const key_type& __k) const { return __tree_.find(__k); }
      |                                                                                                           ^
/usr/include/c++/v1/map:1341:93: note: in instantiation of member function 'std::map<SceNpRoomId, unsigned int>::find' requested here
 1341 |   [[__nodiscard__]] _LIBCPP_HIDE_FROM_ABI bool contains(const key_type& __k) const { return find(__k) != end(); }
      |                                                                                             ^
../rpcs3-9999/rpcs3/Emu/NP/np_notifications.cpp:372:30: note: in instantiation of member function 'std::map<SceNpRoomId, unsigned int>::contains' requested here
  372 |                 if (!pending_quickmatching.contains(room_info->room_status.id))
      |                                            ^
/usr/include/c++/v1/__functional/operations.h:374:60: note: candidate template ignored: substitution failure [with _T1 = const SceNpRoomId &, _T2 = const SceNpRoomId &]: invalid operands to binary expression ('const SceNpRoomId' and 'const SceNpRoomId')
  374 |   _LIBCPP_CONSTEXPR_SINCE_CXX14 _LIBCPP_HIDE_FROM_ABI auto operator()(_T1&& __t, _T2&& __u) const
      |                                                            ^
  375 |       noexcept(noexcept(std::forward<_T1>(__t) < std::forward<_T2>(__u))) //
  376 |       -> decltype(std::forward<_T1>(__t) < std::forward<_T2>(__u)) {
      |                                          ~
In file included from ../rpcs3-9999/rpcs3/Emu/NP/np_notifications.cpp:1:
In file included from ../rpcs3-9999/rpcs3/stdafx.h:6:
In file included from ../rpcs3-9999/Utilities/Config.h:5:
In file included from ../rpcs3-9999/rpcs3/util/logs.hpp:3:
In file included from /usr/include/c++/v1/map:602:
In file included from /usr/include/c++/v1/__tree:42:
/usr/include/c++/v1/__utility/lazy_synth_three_way_comparator.h:44:57: error: no matching function for call to object of type 'const std::less<void>'
   44 |   _LIBCPP_HIDE_FROM_ABI bool __greater() const { return __comp_(__rhs_, __lhs_); }
      |                                                         ^~~~~~~
/usr/include/c++/v1/__tree:1824:27: note: in instantiation of member function 'std::__lazy_compare_result<std::less<void>, SceNpRoomId, SceNpRoomId>::__greater' requested here
 1824 |     } else if (__comp_res.__greater()) {
      |                           ^
/usr/include/c++/v1/__tree:1331:39: note: in instantiation of function template specialization 'std::__tree<std::__value_type<SceNpRoomId, unsigned int>, std::__map_value_compare<SceNpRoomId, std::pair<const SceNpRoomId, unsigned int>, std::less<SceNpRoomId>>, std::allocator<std::pair<const SceNpRoomId, unsigned int>>>::__find_equal<SceNpRoomId>' requested here
 1331 |     return const_cast<__tree*>(this)->__find_equal(__v);
      |                                       ^
/usr/include/c++/v1/__tree:1217:26: note: in instantiation of function template specialization 'std::__tree<std::__value_type<SceNpRoomId, unsigned int>, std::__map_value_compare<SceNpRoomId, std::pair<const SceNpRoomId, unsigned int>, std::less<SceNpRoomId>>, std::allocator<std::pair<const SceNpRoomId, unsigned int>>>::__find_equal<SceNpRoomId>' requested here
 1217 |     auto [__, __match] = __find_equal(__key);
      |                          ^
/usr/include/c++/v1/map:1314:107: note: in instantiation of function template specialization 'std::__tree<std::__value_type<SceNpRoomId, unsigned int>, std::__map_value_compare<SceNpRoomId, std::pair<const SceNpRoomId, unsigned int>, std::less<SceNpRoomId>>, std::allocator<std::pair<const SceNpRoomId, unsigned int>>>::find<SceNpRoomId>' requested here
 1314 |   [[__nodiscard__]] _LIBCPP_HIDE_FROM_ABI const_iterator find(const key_type& __k) const { return __tree_.find(__k); }
      |                                                                                                           ^
/usr/include/c++/v1/map:1341:93: note: in instantiation of member function 'std::map<SceNpRoomId, unsigned int>::find' requested here
 1341 |   [[__nodiscard__]] _LIBCPP_HIDE_FROM_ABI bool contains(const key_type& __k) const { return find(__k) != end(); }
      |                                                                                             ^
../rpcs3-9999/rpcs3/Emu/NP/np_notifications.cpp:372:30: note: in instantiation of member function 'std::map<SceNpRoomId, unsigned int>::contains' requested here
  372 |                 if (!pending_quickmatching.contains(room_info->room_status.id))
      |                                            ^
/usr/include/c++/v1/__functional/operations.h:374:60: note: candidate template ignored: substitution failure [with _T1 = const SceNpRoomId &, _T2 = const SceNpRoomId &]: invalid operands to binary expression ('const SceNpRoomId' and 'const SceNpRoomId')
  374 |   _LIBCPP_CONSTEXPR_SINCE_CXX14 _LIBCPP_HIDE_FROM_ABI auto operator()(_T1&& __t, _T2&& __u) const
      |                                                            ^
  375 |       noexcept(noexcept(std::forward<_T1>(__t) < std::forward<_T2>(__u))) //
  376 |       -> decltype(std::forward<_T1>(__t) < std::forward<_T2>(__u)) {
      |                                          ~
2 errors generated.
```

**Comment by oltolm** [comment]
Looks like it will be fixed in Clang 22.0.2. I would simply wait.

**Comment by v-fox** [comment]
> Looks like it will be fixed in Clang 22.0.2. I would simply wait.

But I'm already using clang-22.1.0, how can there be 22.0.2?
Also, can you link it? Some other apps fail too, like FreeCAD, so I would like to patch it.

**Comment by oltolm** [comment]
I meant 22.1.1 or whatever the next version will be. You linked https://github.com/llvm/llvm-project/issues/179319 and it has been closed as fixed.

**Comment by oltolm** [comment]
Clang version 22.1.1 has not fixed it. Let's wait for 22.1.2.

**Comment by oltolm** [comment]
Can be closed.
