### ISSUE TITLE
Unable to build with Qt 6.10

### ISSUE THREAD

**Issue by engdyn** [RPCS3/rpcs3#17570]
### Quick summary

I'm using the AUR package of RPCS3. Yesterday Qt got updated from 6.9 to 6.10. Since then I'm unable to compile the project.

### Details

I checked the changelog of Qt 6.10 and they added more restrictions on the use of private modules.
> Usage of a private Qt module Foo now requires a call to find_package(Qt6 COMPONENTS FooPrivate) to make the Qt6::FooPrivate target available.

I added `GuiPrivate` to `find_package()` and `Qt6::GuiPrivate` to `target_link_libraries()` in 3rdparty/qt6.cmake which resolved the compiler error.

### Attach a log file

```
/home/erik/.cache/paru/clone/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/gs_frame.cpp:42:10: fatal error: 'qpa/qplatformnativeinterface.h' file not found
   42 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:663: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/gs_frame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3292: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'rpcs3-git-0.0.37.r17986.68d2573344-1':
error: packages failed to build: rpcs3-git-0.0.37.r17986.68d2573344-1
```
