### ISSUE TITLE
Can't compile on linux 64 - multiples errors

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#2236]
Hi all, well i try compile this, but fails for some reason, i'm using gentoo 64:

```
[  4%] Built target png16_static
[  4%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- GIT_VERSION: 4778-684089ba
[  4%] Built target GitVersion
[  5%] Built target shader_code
[  7%] Built target rsx_decompiler
[  7%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/Modules/cellGcmSys.cpp.o
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:64:1: warning: /home/pipe/Documentos/git/rpcs3/rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch: not used because `__STDC_CONSTANT_MACROS' is defined [-Winvalid-pch]
 #endif
 ^
In file included from /home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_decompiler.h:2:0,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/rsx_cache.h:2,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/RSXThread.h:8,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/GSRender.h:3,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/Cell/Modules/cellGcmSys.cpp:8:
/home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_fp_ucode.h:116:23: warning: ‘rsx::fragment_program::OPDEST::<anonymous struct>::opcode’ is too small to hold all values of ‘enum class rsx::fragment_program::opcode_t’
     opcode_t opcode : 6;
                       ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_fp_ucode.h:128:31: warning: ‘rsx::fragment_program::SRC0::<anonymous struct>::reg_type’ is too small to hold all values of ‘enum class rsx::fragment_program::src_reg_type_t’
     src_reg_type_t reg_type : 2;
                               ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_fp_ucode.h:155:31: warning: ‘rsx::fragment_program::SRC1::<anonymous struct>::reg_type’ is too small to hold all values of ‘enum class rsx::fragment_program::src_reg_type_t’
     src_reg_type_t reg_type : 2;
                               ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_fp_ucode.h:195:31: warning: ‘rsx::fragment_program::SRC2::<anonymous struct>::reg_type’ is too small to hold all values of ‘enum class rsx::fragment_program::src_reg_type_t’
     src_reg_type_t reg_type : 2;
                               ^
In file included from /home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_decompiler.h:3:0,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/rsx_cache.h:2,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/RSXThread.h:8,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/GSRender.h:3,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/Cell/Modules/cellGcmSys.cpp:8:
/home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_vp_ucode.h:113:31: warning: ‘rsx::vertex_program::D1::<anonymous struct>::vec_opcode’ is too small to hold all values of ‘enum class rsx::vertex_program::vec_opcode_t’
     vec_opcode_t vec_opcode : 5;
                               ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_vp_ucode.h:114:31: warning: ‘rsx::vertex_program::D1::<anonymous struct>::sca_opcode’ is too small to hold all values of ‘enum class rsx::vertex_program::sca_opcode_t’
     sca_opcode_t sca_opcode : 5;
                               ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../rsx_program_decompiler/rsx_decompiler/rsx_vp_ucode.h:188:39: warning: ‘rsx::vertex_program::SRC::<anonymous struct>::register_type’ is too small to hold all values of ‘enum class rsx::vertex_program::src_register_type’
     src_register_type register_type : 2;
                                       ^
In file included from /home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/gsl.h:24:0,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/../Utilities/GSL.h:7,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/RSXThread.h:14,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/RSX/GSRender.h:3,
                 from /home/pipe/Documentos/git/rpcs3/rpcs3/Emu/Cell/Modules/cellGcmSys.cpp:8:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:157:31: error: ‘constexpr const long int& gsl::index<Rank>::operator[](size_t) const’ cannot be overloaded
     constexpr const_reference operator[](size_t component_idx) const noexcept
                               ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:150:25: error: with ‘constexpr long int& gsl::index<Rank>::operator[](size_t) const’
     constexpr reference operator[](size_t component_idx)
                         ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In constructor ‘constexpr gsl::index<Rank>::index(const value_type (&)[Rank])’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:126:5: error: constexpr constructor does not have empty body
     }
     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: At global scope:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:343:53: error: ‘constexpr gsl::static_bounds_dynamic_range_t::operator T() const [with T = long int; Dummy = void]’ used before its definition
     struct BoundsRanges<dynamic_range, RestRanges...> : BoundsRanges<RestRanges...>
                                                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:343:53: note: in template argument for type ‘long int’ 
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In constructor ‘constexpr gsl::static_bounds<FirstRange, RestRanges ...>::static_bounds(const gsl::static_bounds<Ranges ...>&)’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:624:5: error: constexpr constructor does not have empty body
     }
     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In constructor ‘constexpr gsl::static_bounds<FirstRange, RestRanges ...>::static_bounds(std::initializer_list<long int>)’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:634:5: error: constexpr constructor does not have empty body
     }
     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In constructor ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>::span(std::nullptr_t, IntType)’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1239:5: error: constexpr constructor does not have empty body
     }
     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In constructor ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>::span(gsl::span<ValueType, FirstDimension, RestDimensions>::pointer, gsl::span<ValueType, FirstDimension, RestDimensions>::bounds_type)’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1261:5: error: constexpr constructor does not have empty body
     }
     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In constructor ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>::span(gsl::span<ValueType, FirstDimension, RestDimensions>::pointer, Ptr)’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1271:5: error: constexpr constructor does not have empty body
     }
     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In instantiation of ‘class gsl::span<const gsl::byte, -1l>’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1609:66:   required from here
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(gsl::span<ValueType, FirstDimension, RestDimensions>&&) const [with ValueType = const gsl::byte; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(span&&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: does not match expected signature ‘gsl::span<const gsl::byte, -1l>& gsl::span<const gsl::byte, -1l>::operator=(gsl::span<const gsl::byte, -1l>&&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(const gsl::span<ValueType, FirstDimension, RestDimensions>&) const [with ValueType = const gsl::byte; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(const span&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature ‘gsl::span<const gsl::byte, -1l>& gsl::span<const gsl::byte, -1l>::operator=(const gsl::span<const gsl::byte, -1l>&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In instantiation of ‘class gsl::span<gsl::byte>’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1621:55:   required from here
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(gsl::span<ValueType, FirstDimension, RestDimensions>&&) const [with ValueType = gsl::byte; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(span&&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: does not match expected signature ‘gsl::span<gsl::byte>& gsl::span<gsl::byte>::operator=(gsl::span<gsl::byte>&&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(const gsl::span<ValueType, FirstDimension, RestDimensions>&) const [with ValueType = gsl::byte; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(const span&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature ‘gsl::span<gsl::byte>& gsl::span<gsl::byte>::operator=(const gsl::span<gsl::byte>&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In constructor ‘constexpr gsl::strided_span<ValueType, Rank>::strided_span(gsl::strided_span<ValueType, Rank>::pointer, gsl::strided_span<ValueType, Rank>::size_type, gsl::strided_span<ValueType, Rank>::bounds_type)’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1781:5: error: constexpr constructor does not have empty body
     }
     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In instantiation of ‘class gsl::span<char, -1l>’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/string_span.h:116:78:   required from here
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(gsl::span<ValueType, FirstDimension, RestDimensions>&&) const [with ValueType = char; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(span&&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: does not match expected signature ‘gsl::span<char, -1l>& gsl::span<char, -1l>::operator=(gsl::span<char, -1l>&&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(const gsl::span<ValueType, FirstDimension, RestDimensions>&) const [with ValueType = char; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(const span&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature ‘gsl::span<char, -1l>& gsl::span<char, -1l>::operator=(const gsl::span<char, -1l>&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In instantiation of ‘class gsl::span<const char, -1l>’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/string_span.h:123:90:   required from here
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(gsl::span<ValueType, FirstDimension, RestDimensions>&&) const [with ValueType = const char; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(span&&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: does not match expected signature ‘gsl::span<const char, -1l>& gsl::span<const char, -1l>::operator=(gsl::span<const char, -1l>&&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(const gsl::span<ValueType, FirstDimension, RestDimensions>&) const [with ValueType = const char; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(const span&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature ‘gsl::span<const char, -1l>& gsl::span<const char, -1l>::operator=(const gsl::span<const char, -1l>&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In instantiation of ‘class gsl::span<wchar_t, -1l>’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/string_span.h:130:84:   required from here
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(gsl::span<ValueType, FirstDimension, RestDimensions>&&) const [with ValueType = wchar_t; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(span&&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: does not match expected signature ‘gsl::span<wchar_t, -1l>& gsl::span<wchar_t, -1l>::operator=(gsl::span<wchar_t, -1l>&&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(const gsl::span<ValueType, FirstDimension, RestDimensions>&) const [with ValueType = wchar_t; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(const span&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature ‘gsl::span<wchar_t, -1l>& gsl::span<wchar_t, -1l>::operator=(const gsl::span<wchar_t, -1l>&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h: In instantiation of ‘class gsl::span<const wchar_t, -1l>’:
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/string_span.h:137:96:   required from here
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(gsl::span<ValueType, FirstDimension, RestDimensions>&&) const [with ValueType = const wchar_t; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(span&&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1366:21: error: does not match expected signature ‘gsl::span<const wchar_t, -1l>& gsl::span<const wchar_t, -1l>::operator=(gsl::span<const wchar_t, -1l>&&)’
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: defaulted declaration ‘constexpr gsl::span<ValueType, FirstDimension, RestDimensions>& gsl::span<ValueType, FirstDimension, RestDimensions>::operator=(const gsl::span<ValueType, FirstDimension, RestDimensions>&) const [with ValueType = const wchar_t; long int FirstDimension = -1l; long int ...RestDimensions = {}]’
     constexpr span& operator=(const span&) = default;
                     ^
/home/pipe/Documentos/git/rpcs3/rpcs3/../3rdparty/GSL/include/span.h:1368:21: error: does not match expected signature ‘gsl::span<const wchar_t, -1l>& gsl::span<const wchar_t, -1l>::operator=(const gsl::span<const wchar_t, -1l>&)’
rpcs3/CMakeFiles/rpcs3.dir/build.make:1001: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/Modules/cellGcmSys.cpp.o' failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/Cell/Modules/cellGcmSys.cpp.o] Error 1
CMakeFiles/Makefile2:270: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Thx. Cya.

**Comment by latot** [comment]
note, this seems works over clang, but with gcc fails.

**Comment by latot** [comment]
pass over gcc-5.4 but fails in 4.9.

**Comment by AniLeo** [comment]
What do you mean? It requires GCC 5.1+, won't work with 4.9

**Comment by latot** [comment]
is possible do some checks in the cmake file to avoid this please?

**Comment by al0xf** [comment]
gcc is version is now checked, and the build instructions are updated. This shouldn't be an issue anymore.

**Comment by latot** [comment]
Thx!
