### PR TITLE
Remove SSE4.1 requirement

### LINKED ISSUE #6479: compilation error "error: inlining failed in call to always_inline" on archlinux
```
In file included from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/stdafx.h:28,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.cxx:4,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.hxx:4,
                 from <command-line>:
/tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/types.h: In instantiation of ‘constexpr To std::bit_cast(const From&) [with To = v128; From = v128; <template-parameter-1-3> = void]’:
/tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/BEType.h:454:34:   required from ‘static v128 se_storage<T, 16, 16>::to(const T&) [with T = v128]’
/tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/BEType.h:502:30:   required from ‘se_t<T, true, Align>& se_t<T, true, Align>::operator=(se_t<T, true, Align>::type) [with T = v128; long unsigned int Align = 16; se_t<T, true, Align>::type = v128]’
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/Cell/PPUInterpreter.cpp:3636:53:   required from here
/tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/BEType.h:7:19: note: ‘union v128’ has no user-provided default constructor
    7 | union alignas(16) v128
      |                   ^~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/BEType.h:9:7: note: and the implicitly-defined constructor does not initialize ‘char v128::_bytes [16]’
    9 |  char _bytes[16];
      |       ^~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/immintrin.h:37,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/x86intrin.h:32,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/types.h:6,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/stdafx.h:27,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.cxx:4,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.hxx:4,
                 from <command-line>:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/smmintrin.h: In static member function ‘static bool ppu_interpreter::FCTIWZ(ppu_thread&, ppu_opcode_t)’:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
  447 | _mm_extract_epi32 (__m128i __X, const int __N)
      | ^~~~~~~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/Cell/PPUInterpreter.cpp:4833:61: note: called from here
 4833 |  ppu.fpr[op.frd] = std::bit_cast<f64, s64>(_mm_extract_epi32(res, 0));
      |                                            ~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/immintrin.h:37,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/x86intrin.h:32,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/types.h:6,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/stdafx.h:27,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.cxx:4,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.hxx:4,
                 from <command-line>:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
  447 | _mm_extract_epi32 (__m128i __X, const int __N)
      | ^~~~~~~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/Cell/PPUInterpreter.cpp:4833:61: note: called from here
 4833 |  ppu.fpr[op.frd] = std::bit_cast<f64, s64>(_mm_extract_epi32(res, 0));
      |                                            ~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/immintrin.h:37,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/x86intrin.h:32,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/Utilities/types.h:6,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/stdafx.h:27,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.cxx:4,
                 from /tmp/makepkg/rpcs3-git/src/build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.hxx:4,
                 from <command-line>:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include/smmintrin.h:447:1: error: inlining failed in call to always_inline ‘int _mm_extract_epi32(__m128i, int)’: target specific option mismatch
  447 | _mm_extract_epi32 (__m128i __X, const int __N)
      | ^~~~~~~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/Emu/Cell/PPUInterpreter.cpp:4833:61: note: called from here
 4833 |  ppu.fpr[op.frd] = std::bit_cast<f64, s64>(_mm_extract_epi32(res, 0));
      |                                            ~~~~~~~~~~~~~~~~~^~~~~~~~
make[2]: *** [rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/build.make:743: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/PPUInterpreter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

https://aur.archlinux.org/packages/rpcs3-git/
https://github.com/RPCS3/rpcs3/issues/1546

### PR DESCRIPTION
**Pull request by isJuhn**
Some SSE4.1 code was introduced with https://github.com/RPCS3/rpcs3/commit/a560498cd4d18b4dff820c35f9cb3a5f00fbf630 without updating the build flags thus resulting in #6479.
The `_mm_extract_epi` calls which is the SSE4.1 code in question can easily be replace with a single `_mm_cvtsi128_si` call each since we only access the lower integer. This generates identical code and removes the SSE4.1 requirement. Fixes #6479

### CODE REVIEW

**Comment by amayra** [comment]
finally thank you
