### ISSUE TITLE
[Regression] Broken graphics in GTA games

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#17667]
### Quick summary

GTA games have some effects broken after PR #17666.

### Details

After PR #17666 merged, GTA IV has no lighting in interiors with Vulkan. With OpenGL, it throws a shader compilation error.

And in GTA V, it breaks transparent texture like fences or curtains, and the portrait on the pause menu.

<details>
 <summary>GTA IV</summary>

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/874a32fc-c70f-4d40-a1d7-b293e727191b" />
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/fe6f2f9f-25e1-4545-b1b4-cb59171002b4" />

</details>
<details>
 <summary>GTA V</summary>

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/0e79e418-0d95-4d60-8471-a5ca0715e33f" />
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/3141afb5-7e63-42a0-b8b6-73a2c65d13e3" />

<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/b44b8126-b45c-4800-b5b3-78aeae0fd7ee" />
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/41b5647e-c723-4cec-b72d-591bad263fd8" />

</details>

### Build with regression

v0.0.38-18293-8984c2b3

### Attach two log files

[Log GTA IV GL (Working)](https://github.com/user-attachments/files/23371032/RPCS3.log.gz)
[Log GTA IV GL (Broken)](https://github.com/user-attachments/files/23370993/Log.GTA.IV.GL.5-11-25.gz)

[Log GTA IV VK (Working)](https://github.com/user-attachments/files/23371682/RPCS3.log.gz)
[Log GTA IV VK (Broken)](https://github.com/user-attachments/files/23371581/RPCS3.log.gz)

[Log GTA V VK (Working)](https://github.com/user-attachments/files/23371404/Log.GTA.V.VK.5-11-25.Working.gz)
[Log GTA V VK (Broken)](https://github.com/user-attachments/files/23371231/Log.GTA.V.VK.5-11-25.Broken.gz)

### Attach capture files for visual issues

[RSX Capture GTA IV (Working)](https://drive.google.com/file/d/1VVlo9-a4QFM1m1jTBM_C_5ZSIZ82uRkk/view?usp=sharing)
[RSX Capture GTA IV (Broken)](https://drive.google.com/file/d/1Iq02w0m5HFt_dQXjBZ7Cjkxf1cdNloVb/view?usp=sharing)

[RSX Capture 1 GTA V (Working)](https://drive.google.com/file/d/1r-EwZYwS4CGeKDjmh6jO9GkrXUAd3LsB/view?usp=sharing)
[RSX Capture 1 GTA V (Broken)](https://drive.google.com/file/d/1bxtJWJzEEhlSwkf2QW0pywwcbXtJAIw8/view?usp=sharing)

[RSX Capture 2 GTA V (Working)](https://drive.google.com/file/d/17vQf8My-QoRI_F1lFyS4fvGONFrGvVJH/view?usp=sharing)
[RSX Capture 2 GTA V (Broken)](https://drive.google.com/file/d/1A2rmwVCeD_o2CZxi_kYOvOTVSudR3h2q/view?usp=sharing)

### System configuration

OS: Windows 11 21H2
CPU: Intel Core i7-7700HQ
RAM: 16 GB RAM
GPU: NVIDIA GeForce GTX 1060 (581.80)

**Comment by kd-11** [comment]
The compiled output does not match the source code. The build cache must be out of sync.
I have confirmed that OpenGL is fine when compiled locally and generates different code.

**Comment by kd-11** [comment]
@MarioSonic2987 Check the new artifacts: https://github.com/RPCS3/rpcs3/actions/runs/19112136517

**Comment by kd-11** [comment]
Builds have been republished. I'll close this as the screenshots posted in discord show the problem is fixed after rebuild.
