### ISSUE TITLE
LLVM doesn't compile on VS 16.9.2

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#10022]
On VS 16.9.2 LLVM won't compile. This potentially will be an issue once azure is on that version.
The errors:
`1>C:\Users\redacted\Desktop\rpcs3\llvm\include\llvm/Support/DebugCounter.h(80,1): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`
`1>C:\Users\redacteds\Desktop\rpcs3\llvm\include\llvm/Support/SuffixTree.h(278,1): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`
`1>C:\Users\redacted\Desktop\rpcs3\llvm\lib\Support\SuffixTree.cpp(85,46): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`
`1>C:\Users\redacted\Desktop\rpcs3\llvm\lib\Support\VirtualFileSystem.cpp(1257,1): error C2666: 'llvm::DenseMapIterator<KeyT,ValueT,KeyInfoT,BucketT,false>::operator ==': 2 overloads have similar conversions [C:\Users\redacted\Desktop\rpcs3\llvm_build\lib\Support\LLVMSupport.vcxproj]`
