### ISSUE TITLE
How to compile with llvm-3.9?

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#2247]
Hi all, well i'm trying to compile this with llvm-3.9, with little changes i can reach the last step of compilation, what can you recommend with this?

```
[  4%] Built target png16_static
[  4%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- GIT_VERSION: 4784-9e84804e
[  4%] Built target GitVersion
[  6%] Built target rsx_decompiler
[  7%] Built target shader_code
[  7%] Linking CXX executable ../bin/rpcs3
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/rpcs3.dir/Emu/Cell/PPUTranslator.cpp.o: undefined reference to symbol '_ZN4llvm12ConstantExpr16getShuffleVectorEPNS_8ConstantES2_S2_PNS_4TypeE'
/usr/lib64/libLLVMCore.so.39: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
rpcs3/CMakeFiles/rpcs3.dir/build.make:10544: recipe for target 'bin/rpcs3' failed
make[2]: *** [bin/rpcs3] Error 1
CMakeFiles/Makefile2:270: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Thx. Cya.

**Comment by AniLeo** [comment]
RPCS3 has not been updated to work with LLVM 3.9, it currently uses 3.8
See https://github.com/RPCS3/rpcs3/issues/1870#issuecomment-250778366

**Comment by latot** [comment]
:O ..., i expect problems but seems is more, only if you like, how can fix this last part to compile? (only to have this as a reference)

And to complement, to compile with llvm-3.9 in the file Emu/Cell/PPUThread.cpp b/rpcs3/Emu/Cell/PPUThread.cpp, is necessary add:
```
#include "llvm/Transforms/Scalar/GVN.h"
```

Thx. Cya.

**Comment by AniLeo** [comment]
See, even if you get it to compile with 3.9 without errors it will probably just crash or leak memory as described by Nekotekina, so don't do it unless you can fix the bugs there are currently preventing the update.

**Comment by latot** [comment]
yep, i mean only as a reference, i'm agree update to 3.9 is bad idea now.

**Comment by raven02** [comment]
Closed as llvm upgraded to 3.9
