### ISSUE TITLE
SPURecompiler doesn't build under Linux

### ISSUE THREAD

**Issue by Bigpet** [RPCS3/rpcs3#203]
We should remove the `#ifdefs` introduced in #202. I'm going to paste the compilation errors
