### ISSUE TITLE
Fails to build with FFmpeg 8.0 (-DUSE_SYSTEM_FFMPEG=ON)

### ISSUE THREAD

**Issue by jbeich** [RPCS3/rpcs3#17461]
### Quick summary

FFmpeg 8.0 was [released](https://ffmpeg.org/index.html#news) on 2025-08-22, so some distros are working on updating the package.

```c++
$ cmake -G Ninja -B _build -DUSE_SYSTEM_FFMPEG=ON
$ cmake --build _build
[...]
rpcs3/Emu/Cell/Modules/cellAtracXdec.cpp:114:33: error: use of undeclared identifier 'AV_CODEC_CAP_SUBFRAMES'
  114 |         ensure(!(codec->capabilities & AV_CODEC_CAP_SUBFRAMES));
      |                                        ^
rpcs3/Emu/Cell/Modules/cellAtracXdec.cpp:159:16: error: use of undeclared identifier 'avcodec_close'
  159 |         if (int err = avcodec_close(ctx); err)
      |                       ^
```
### References
- AV_CODEC_CAP_SUBFRAMES: [deprecation](https://github.com/ffmpeg/ffmpeg/commit/8b20d0dcb5cf), [removal](https://github.com/ffmpeg/ffmpeg/commit/c29a1cbd03d5)
- avcodec_close: [deprecation](https://github.com/ffmpeg/ffmpeg/commit/1cc24d749569), [removal](https://github.com/ffmpeg/ffmpeg/commit/0d48da2db0b2)

**Comment by jbeich** [comment]
Oops, forgot to reference API deprecation preceding the removal:
https://github.com/ffmpeg/ffmpeg/commit/8b20d0dcb5cf
https://github.com/ffmpeg/ffmpeg/commit/1cc24d749569
