### PR TITLE
rsx: Bug fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Fix stencil clear values - https://github.com/RPCS3/rpcs3/issues/2810
- Fix some buffer misalignment crashes when using debuggers or faulty drivers
- Fix an old regression with God of War I and II from the collection - https://github.com/RPCS3/rpcs3/issues/2626
- Fix openGL clip space conversion (Z symmetry)
- Add a workaround to fix shadow map generation
- Add hardware PCF shadow support
- Fix stencil buffer reset (Still a workaround atm)
- Remove several hundred compilation warnings from rsx code
- Improve SPIRV compilation speed by avoiding unnecessary SH context (re)creattion
- Add a needed rsx method for wipeout HD
- Fix index buffer generation when using a non-zero base offset
- Drop vs user files from the repo
- Added a toggle to ensure strict rendering mode. Currently only affects framebuffer feedback loops. When disabled, we ignore the feedback loop in vulkan and issue a texture barrier in ogl. When enabled, a duplicate texture is created to ensure this is not an issue but there is a tangible performance penalty. Defaults to OFF
- Re-organized the graphics options tab a bit to separate main options from debugging options.

Current bugs
- [x] Crash compiling textureProj due to PCF samplers support
- [x] Crash when debug overlay is enabled (vulkan only)

### CODE REVIEW

**Comment by MarioSonic2987** [comment]
**This PR**:
image 1
**Master**:
image

**Comment by Xcedf** [comment]
Confirm GoW issue is fixed, also fixed same depth issue in Ni No Kuni Demo

**Comment by kd-11** [comment]
Markiing as WIP since touching this has uncovered alot of other issues.

**Comment by woj1993** [comment]
@kd-11 What issues?
PS. Are you sure this is best option? I worry you fix might stay marked as WIP too long and will need another rewrite if it isn't merged now.

**Comment by AniLeo** [comment]
@woj1993 no need to worry, it will get merged relatively soon. We're running internal tests.

**Comment by Xcedf** [comment]
Dante's Inferno colors fixed

**Comment by takhlaq** [comment]
**The Legend of Heroes: Trails of Cold Steel [BLUS31572]**
looks good
Trails of Cold Steel

**Comment by Xcedf** [comment]
Magnificent changes, now have perfect shadows in Tekken6 and Soul Calibur IV
but i also have a slowdown in some games if compare to master
here's the example,
master

this pr

will try to find more specific commit later

**Comment by kd-11** [comment]
Disable the invalidate cache option. Should fix performance. Report if it does not.

**Comment by Xcedf** [comment]
Unfortunately not, doesn't affect performance at all tried both on and off
another example of fps drop Heavy Rain Demo menu
master 18fps
this pr 14fps

**Comment by kd-11** [comment]
Odd. I'll look into it.

**Comment by vadisave** [comment]
Demon's souls reborn with this PR
before
after

**Comment by Xcedf** [comment]
Another issue
several games are fail to compile shaders
Army of Two
Lolipop Chainsaw
OGL:
F {rsx::thread} : class gl::glsl::link_exception thrown: linkage failed: 'Fragment info
-------------
0(115) : error C1031: swizzle mask element not present in operand "xyz"
0(128) : error C1031: swizzle mask element not present in operand "xyz"
0(130) : error C1031: swizzle mask element not present in operand "xyz"
0(133) : error C1031: swizzle mask element not present in operand "xyz"
(0) : error C2003: incompatible options for link
Vulkan:
E {rsx::thread} RSX: ERROR: 0:125: 'xyz' : vector swizzle selection out of range 
ERROR: 0:125: 'assign' :  cannot convert from ' global highp float' to ' temp highp 3-component vector of float'
ERROR: 0:125: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
E {rsx::thread} RSX: 
F {rsx::thread} : class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:492)

**Comment by Xcedf** [comment]
Another issue
several games are fail to compile shaders
Army of Two
Lolipop Chainsaw
OGL:
F {rsx::thread} : class gl::glsl::link_exception thrown: linkage failed: 'Fragment info

0(115) : error C1031: swizzle mask element not present in operand "xyz"
0(128) : error C1031: swizzle mask element not present in operand "xyz"
0(130) : error C1031: swizzle mask element not present in operand "xyz"
0(133) : error C1031: swizzle mask element not present in operand "xyz"
(0) : error C2003: incompatible options for link
Vulkan:
E {rsx::thread} RSX: ERROR: 0:125: 'xyz' : vector swizzle selection out of range
ERROR: 0:125: 'assign' : cannot convert from ' global highp float' to ' temp highp 3-component vector of float'
ERROR: 0:125: '' : compilation terminated
ERROR: 3 compilation errors. No code generated.
E {rsx::thread} RSX:
F {rsx::thread} : class std::runtime_error thrown: Failed to compile fragment shader
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKFragmentProgram.cpp:492)

**Comment by kd-11** [comment]
Thats new with this build? If so, attach fragmentprogram.spirv here

**Comment by Xcedf** [comment]
Yes it's on this build, master is fine, here's the new files
https://mega.nz/#!rcZWmYrL!d01JENkZUAx514DmAB7hi7Xa1qL6HOBMZxpqngjJ9MQ

**Comment by Sora3100** [comment]
OpenGL:
y81wz 1

Vulkan:
g4uax 1

I can also confirm that Xillia 1/2 now displays shadows

**Comment by MarioSonic2987** [comment]
Many games are improved with this PR:
gtav
nsunsr
ssbs
tekkenrevolution

**Comment by Xcedf** [comment]
Some info about my issues:
performance regression caused by cd3d7efe or previous 86465e96(but it has compilation issues, so can't tell for sure now)

**Comment by kd-11** [comment]
Thanks alot. Its probably the former since it copies a texture in GPU memory and spams the log. Not sure it should be disabled though as using a current render target as input is a spec violation. I need to check for a way around that.

**Comment by Xcedf** [comment]
You're welcome
As for shader compilation issue: commit afb47652 is the cause

**Comment by Xcedf** [comment]
You're welcome
As for shader compilation issue: commit b31d937 is the cause
edited my pervious commit, gave wrong revision sorry

**Comment by kd-11** [comment]
Disabling those lines allows for a pretty serious spec violation that causes heavy flickering and broken graphics in some cases. It needs some more work to prevent the slowdown.

**Comment by Grima04** [comment]
Grand Theft Auto V BLES01807

F 0:04:29.285507 {rsx::thread} class gl::glsl::link_exception thrown: linkage failed: 'Vertex info
0(77) : error C0000: syntax error, unexpected '.', expecting ')' at token "."
(0) : error C2003: incompatible options for link

LOG: 
[RPCS3_GTAV_22-06-2017.zip](https://github.com/RPCS3/rpcs3/files/1094687/RPCS3_GTAV_22-06-2017.zip)

Video: 
https://www.youtube.com/watch?v=YUn41FgN6eE

File: rpcs3/Emu/RSX/VK/VKTextureCache.h [hunk 1]
```diff
@@ -422,16 +474,37 @@ namespace vk
 			vk::image *rtt_texture = nullptr;
 			if (rtt_texture = m_rtts.get_texture_from_render_target_if_applicable(texaddr))
 			{
+				if (g_cfg.video.strict_rendering_mode)
+				{
+					for (auto tex : m_rtts.m_bound_render_targets)
```
Comment (danilaml) [inline rpcs3/Emu/RSX/VK/VKTextureCache.h]: Why not `const auto &tex`?

File: rpcs3/Emu/RSX/GL/GLTextureCache.h [hunk 2]
```diff
@@ -663,15 +663,60 @@ namespace gl
 			/**
 			 * Check for sampleable rtts from previous render passes
 			 */
-			gl::texture *texptr = nullptr;
+			gl::render_target *texptr = nullptr;
 			if (texptr = m_rtts.get_texture_from_render_target_if_applicable(texaddr))
 			{
+				for (auto tex : m_rtts.m_bound_render_targets)
```
Comment (danilaml) [inline rpcs3/Emu/RSX/GL/GLTextureCache.h]: Here too.

**Comment by Xcedf** [comment]
Confirm, both issues i've reported are fixed now, great work as usual

**Comment by uvraj** [comment]
unbenannt
having loadscreen issues

**Comment by uvraj** [comment]
unbenannt
PR looks good so far

**Comment by uvraj** [comment]
F {rsx::thread} class std::runtime_error thrown: Unknown texture dimension 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:137)                                                                 getting this error

**Comment by uvraj** [comment]
unbenannt
games like minecraft are running pretty well :)

**Comment by kd-11** [comment]
This was merged and closed 2 weeks ago. Latest rsx PR is https://github.com/RPCS3/rpcs3/pull/3026
