### ISSUE TITLE
fail build with Qt 5.11.0(rc0)

### ISSUE THREAD

**Issue by sl1pkn07** [RPCS3/rpcs3#4537]
~~~bash
[ 75%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/settings_dialog.cpp.o
cc1plus: warning: /tmp/makepkg/rpcs3-git/src/build/rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch: not used because `__STDC_CONSTANT_MACROS' is defined [-Winvalid-pch]
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp: In constructor 'settings_dialog::settings_dialog(std::shared_ptr<gui_settings>, std::shared_ptr<emu_settings>, const int&, QWidget*, const GameInfo*)':
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:151:45: error: invalid use of incomplete type 'class QButtonGroup'
  QButtonGroup *ppuBG = new QButtonGroup(this);
                                             ^
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:152:7: error: invalid use of incomplete type 'class QButtonGroup'
  ppuBG->addButton(ui->ppu_precise, (int)ppu_decoder_type::precise);
       ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:153:7: error: invalid use of incomplete type 'class QButtonGroup'
  ppuBG->addButton(ui->ppu_fast,    (int)ppu_decoder_type::fast);
       ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:154:7: error: invalid use of incomplete type 'class QButtonGroup'
  ppuBG->addButton(ui->ppu_llvm,    (int)ppu_decoder_type::llvm);
       ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:164:10: error: invalid use of incomplete type 'class QButtonGroup'
     ppuBG->button(i)->setChecked(true);
          ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:167:17: error: invalid use of incomplete type 'class QButtonGroup'
    connect(ppuBG->button(i), &QAbstractButton::pressed, [=]()
                 ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:180:45: error: invalid use of incomplete type 'class QButtonGroup'
  QButtonGroup *spuBG = new QButtonGroup(this);
                                             ^
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:181:7: error: invalid use of incomplete type 'class QButtonGroup'
  spuBG->addButton(ui->spu_precise, (int)spu_decoder_type::precise);
       ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:182:7: error: invalid use of incomplete type 'class QButtonGroup'
  spuBG->addButton(ui->spu_fast,    (int)spu_decoder_type::fast);
       ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:183:7: error: invalid use of incomplete type 'class QButtonGroup'
  spuBG->addButton(ui->spu_asmjit,  (int)spu_decoder_type::asmjit);
       ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:184:7: error: invalid use of incomplete type 'class QButtonGroup'
  spuBG->addButton(ui->spu_llvm,    (int)spu_decoder_type::llvm);
       ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:194:10: error: invalid use of incomplete type 'class QButtonGroup'
     spuBG->button(i)->setChecked(true);
          ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:197:17: error: invalid use of incomplete type 'class QButtonGroup'
    connect(spuBG->button(i), &QAbstractButton::pressed, [=]()
                 ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:216:49: error: invalid use of incomplete type 'class QButtonGroup'
  QButtonGroup *libModeBG = new QButtonGroup(this);
                                                 ^
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:217:11: error: invalid use of incomplete type 'class QButtonGroup'
  libModeBG->addButton(ui->lib_auto, (int)lib_loading_type::automatic);
           ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:218:11: error: invalid use of incomplete type 'class QButtonGroup'
  libModeBG->addButton(ui->lib_manu, (int)lib_loading_type::manual);
           ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:219:11: error: invalid use of incomplete type 'class QButtonGroup'
  libModeBG->addButton(ui->lib_both, (int)lib_loading_type::both);
           ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:220:11: error: invalid use of incomplete type 'class QButtonGroup'
  libModeBG->addButton(ui->lib_lv2,  (int)lib_loading_type::liblv2only);
           ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:228:13: error: invalid use of incomplete type 'class QButtonGroup'
    libModeBG->button(i)->setText(libmode_list[i]);
             ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:232:14: error: invalid use of incomplete type 'class QButtonGroup'
     libModeBG->button(i)->setChecked(true);
              ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:235:21: error: invalid use of incomplete type 'class QButtonGroup'
    connect(libModeBG->button(i), &QAbstractButton::pressed, [=]()
                     ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:329:76: error: incomplete type 'QButtonGroup' used in nested name specifier
  connect(libModeBG, static_cast<void(QButtonGroup::*)(int)>(&QButtonGroup::buttonClicked), l_OnLibButtonClicked);
                                                                            ^~~~~~~~~~~~~
/tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:341:24: error: invalid use of incomplete type 'class QButtonGroup'
  int buttid = libModeBG->checkedId();
                        ^~
In file included from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /tmp/makepkg/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/settings_dialog.cpp:2:
/usr/include/qt/QtWidgets/qabstractbutton.h:53:7: note: forward declaration of 'class QButtonGroup'
 class QButtonGroup;
       ^~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-unused-command-line-argument'
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:4113: rpcs3/CMakeFiles/rpcs3.dir/rpcs3qt/settings_dialog.cpp.o] Error 1
make[2]: Leaving directory '/tmp/makepkg/rpcs3-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:219: rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make[1]: Leaving directory '/tmp/makepkg/rpcs3-git/src/build'
make: *** [Makefile:130: all] Error 2
~~~

rpcs3 737db90058beb93d83d12ea94c405476ee594bfc
Qt 5.11.0rc
cmake 3.11.1
gcc 8.1.0

**Comment by AniLeo** [comment]
Use Qt 5.10.X, it's the latest release.

**Comment by Megamouse** [comment]
try to add 
`#include <QButtonGroup>`
to settings_dialog.cpp

**Comment by sl1pkn07** [comment]
tnx @Megamouse , fixed.

PR with the fix?

greetings

**Comment by AniLeo** [comment]
Fixed via  #4637
