### ISSUE TITLE
DX12/OGL/VK: Dai-3-Ji Super Robot Taisen Z Jigoku-hen bootup black screen 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1761]
Title screen should be working now in all backend .However , It is still rendering black at booting for all backend due to R/W buffers behavior  .It should display something at below .

![1](https://cloud.githubusercontent.com/assets/3000282/15890332/82503e88-2da1-11e6-8bf3-17798ea3be53.jpg)
![2](https://cloud.githubusercontent.com/assets/3000282/15890333/82899d86-2da1-11e6-8950-1c66ff64165e.jpg)
![3](https://cloud.githubusercontent.com/assets/3000282/15890334/82e7a5b6-2da1-11e6-965e-0c2bbea42cfb.jpg)
![4](https://cloud.githubusercontent.com/assets/3000282/15890335/83499a14-2da1-11e6-80ad-014103999d9d.jpg)

**Comment by raven02** [comment]
@kd-11 feel free to put update here for this r/w buffers issue.

**Comment by kd-11** [comment]
It doesn't seem to be trivial since only reading buffer data from cell during init has no effect whatsoever. A better approach will have to be implemented.
@raven02 can you test dh's rsx_cache branch? I heard some stuff was fixed on there but that was a while back.

**Comment by raven02** [comment]
Sure let me check it out on rsx_cache branch

**Comment by raven02** [comment]
Just built rsx_cache - 
[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/305110/rpcs3.zip)

It is still black screen at bootup even with r/w color buffers enabled.

**Comment by kd-11** [comment]
After looking deeper, i'm almost sure that this is not related to cell read/write framebuffer support. I'm not certain how the game expects textures it did not set up to manifest, but its verty likely that there's memory corruption going on in this game. The fact that one has to press a key combo to show the start screen could be proof of this.

**Comment by raven02** [comment]
Humm probably not an easy fix at this moment i believe if it is memory corruption .

**Comment by raven02** [comment]
For some reasons , the movie is now looping without progressing in latest build . Will check out which commit regressed.

**Comment by raven02** [comment]
@AniLeo / @SakataGintokiYT . It would be appreciated if you can help to test the following commit to see which start broken.

https://ci.appveyor.com/api/buildjobs/j1h5x2x0javsprk1/artifacts/rpcs3-ReleaseLLVM-2159ad61.zip

https://ci.appveyor.com/api/buildjobs/8nab460wartbxes3/artifacts/rpcs3-ReleaseLLVM-065e8428.zip

**Comment by raven02** [comment]
Thanks for Onelight . This game is able to in-game now with the SDAT file decrption under PS3_GAME\USRDIR\DATA\STAGE.

Probably it is similar case for some other games that

**Comment by raven02** [comment]
Savedata is working in 0.0.0.6 but looks like got broken in 0.0.0.9

**Comment by raven02** [comment]
Loading save data and continue mission all working again by https://github.com/RPCS3/rpcs3/pull/1910

**Comment by raven02** [comment]
Using OpenGL , intro movie or in-game fight battle sometime will crash with shader error below (DX12 is prefectly fine btw)

{rsx::thread} class gl::glsl::compilation_exception thrown: compilation failed: 
ERROR: 0:146: 'tex2' : undeclared identifier 
ERROR: 0:151: 'tex3' : undeclared identifier 
ERROR: 0:154: 'tex4' : undeclared identifier 
ERROR: 0:157: 'tex5' : undeclared identifier

**Comment by kd-11** [comment]
Any steps to reproduce opengl crash?

**Comment by raven02** [comment]
Yep , it basically can reproduce all the time at the same point . It is 2nd intro movie playback .It will stuck at the following pic

![untitled](https://cloud.githubusercontent.com/assets/3000282/16876381/3a8e551a-4ad6-11e6-8b2f-8ee9fcffa1a9.jpg)

**Comment by raven02** [comment]
I'm close this one since it mixed with different issue .
