### ISSUE TITLE
Dependency Needed

### ISSUE THREAD

**Issue by mmhobi7** [RPCS3/rpcs3#704]
I attempted to build on ubuntu 14.10 but ran into error 2. I seem to be missing avcodec.h which is from FFmpeg. Here is a snip of what the error said:
/home/aaahh/rpcs3/rpcs3/Emu/SysCalls/Modules/cellAdec.cpp:13:32: fatal error: libavcodec/avcodec.h: No such file or directory
I'm I doing something wrong or am I correct to assume that FFmpeg should be added to the dependency list? FFmpeg isn't available in the official, it has to be compiled manually.
