### PR TITLE
AAA fixes

### PR DESCRIPTION
**Pull request by kd-11**
- Separate texture read barrier from full pipeline barriers and avoids a lot of unnecessary sync/work caused by doing a full sync for texture read barriers. Applications tend to spam a lot of the texture read barriers so its better to let the cache deal with a raw miss than to try and optimize with a barrier hint.
- ZCULL: Implement targeted synchronization to avoid stalling for too long gathering results that may be unused.
- ZCULL: Defer conditional render evaluation to avoid a hard stall whenever a conditional render register is touched.
- ZCULL: Change from arbitrary counters to microsecond counters to determine evaluation deadlines. The result is much more consistent throughput and latency.
- Improve aliased memory contention evaluation. It is common for the same memory address to be used as both a color target and depth target in a draw, but configuration registers ultimately determine whether the hardware will write depth or color, or both and one overwrites the other.
- Fix a vulkan regression (https://github.com/RPCS3/rpcs3/issues/4923)
- Improve rsx timestamp accuracy to simulate nanosecond timing.
- Fix blit engine writes to active rendertargets for vulkan.
- Improve vm deadlock evasion; should avoid some situations that would cause the emulator to lock up and die (e.g prince of persia, warrior within)
- Improve memory tracking so that writing to a large block of memory should reach any framebuffers that live in the disturbed range. Only basic invalidation has been done right now.
- Enable swizzle formats for all textures unless proven otherwise. Tests have shown that Z scanning is valid for almost all formats except some special compressed ones like DXT.
- vk/gl: Several minor optimizations to hash functions and resource management to squeeze out a few more frames in some applications.

### CODE REVIEW

**Comment by Kravickas** [comment]
**Far Cry 2**
Driver crash on Vulkan before menu
obrazek
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2281359/RPCS3.log)

**Comment by creeperjedi** [comment]
With this Pr, Infamous now has these weird boxes on the left side of the screen. (See pictures)

Pr:
infamous - aaa fixes pr
[Infamous - AAA Fixes Pr.log.gz](https://github.com/RPCS3/rpcs3/files/2281362/Infamous.-.AAA.Fixes.Pr.log.gz)


v0.0.5-7177 (Master at time of writing):
infamous - v0 0 5-7177
[Infamous - v0.0.5-7177.gz](https://github.com/RPCS3/rpcs3/files/2281363/Infamous.-.v0.0.5-7177.gz)

**Comment by legend800** [comment]
Most everything I've tried so far is unstable. Wipeout HD, Captain America, Backbreaker all freeze when loading or just entering gameplay. No change in GTI Club which does not get along with RSX. 

Freeze points:
2018-08-12 14_56_18-notes docx - microsoft word

2018-08-12 14_59_22-fps_ 58 21 _ vulkan _ 0 0 5-0a30c563-rsx_volatile _ captain america _ super sold

(Backbreaker occurs on the first challenge every time)

[RPCS3-wipeout.log.gz](https://github.com/RPCS3/rpcs3/files/2281385/RPCS3-wipeout.log.gz)
[RPCS3-backbreaker.log.gz](https://github.com/RPCS3/rpcs3/files/2281386/RPCS3-backbreaker.log.gz)

Flickering in Rayman Legends is NOT fixed either, despite that GH issue being closed (even with Strict on).

**Comment by Zangetsu38** [comment]
@legend800 freeze for Wipeout HD no relate this PR, is old regression

**Comment by legend800** [comment]
@Zangetsu38 No, Wipeout HD has no stability issues for the past year. I test it almost every week. Rock solid for me. I finally traced it down to TSX and disabling it fixed the game and probably unrelated. I'll do a pass on everything again with this off and update the previous comments in the next hour.

**Comment by stride21** [comment]
Infamous 2 
PR:
infams kd

Master:
main

This PR also fix an issue with the game hanging so now you can progress further in the story.

**Comment by Kravickas** [comment]
**GTA V**
OGL (flush request : 2 speculations)
ogl kd

Vulkan - freeze emu after few second ingame (flush request : 2 speculations)
vulkan kd

Master 
obrazek

**Comment by greentop** [comment]
GCC build on Ubuntu 16.04 (Travis is borked atm to get this far).

```
In file included from /home/green/rpcs3/rpcs3/Emu/RSX/Capture/rsx_capture.cpp:5:0:
/home/green/rpcs3/rpcs3/Emu/RSX/Common/surface_store.h: In lambda function:
/home/green/rpcs3/rpcs3/Emu/RSX/Common/surface_store.h:213:6: error: need ‘typename’ before ‘rsx::surface_hierachy_info<typename Traits::surface_type>::memory_overlap_t’ because ‘rsx::surface_hierachy_info<typename Traits::surface_type>’ is a dependent scope
      surface_hierachy_info<surface_type>::memory_overlap_t overlap;
      ^
/home/green/rpcs3/rpcs3/Emu/RSX/Common/surface_store.h:213:60: error: expected ‘;’ before ‘overlap’
      surface_hierachy_info<surface_type>::memory_overlap_t overlap;
                                                            ^
/home/green/rpcs3/rpcs3/Emu/RSX/Common/surface_store.h:214:6: error: ‘overlap’ was not declared in this scope
      overlap._ref = surface;
      ^
[ 87%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/Common/FragmentProgramDecompiler.cpp.o
[ 87%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/Common/ProgramStateCache.cpp.o
rpcs3/CMakeFiles/rpcs3.dir/build.make:4676: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/Capture/rsx_capture.cpp.o' failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/RSX/Capture/rsx_capture.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1563: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JohnGodgames** [comment]
The last of us crashes when WCB is enabled.

tlou aaa


[tlou RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2282006/tlou.RPCS3.log.gz)

[tlou shaderlog.zip](https://github.com/RPCS3/rpcs3/files/2282011/tlou.shaderlog.zip)

**Comment by Asinin3** [comment]
@legend800 Very likely caused by https://github.com/RPCS3/rpcs3/pull/4920 same issue is seen with RDR if TSX is enabled you can't go ingame after SPU Realms merged.

**Comment by spyropt** [comment]
@legend800 that problem happens without tsx also, it has happened to me alot of times testing Wipeout, so it's not related to this pr

**Comment by Lagahan** [comment]
@Asinin3 Is #4920 included in this branch at the moment? Wipeout doesn't display graphics under SPU LLVM on this branch, which was something that was fixed in #4920.
I'm also getting the crash with TSX enabled though, haven't had any stability issues with it on master since around February.

**Comment by Dokman** [comment]
i am using ryzen and i don't have the problem of TSX so all games are displaying very good graphics Wipout is going okay with Little glitches but is working

**Comment by Asinin3** [comment]
This was rebased and the PR was opened after SPU Realms was merged, so yes SPU Realms is in these builds.

**Comment by stride21** [comment]
Resistance 3 with this PR shows still transparent images over the gameplay which can frequently disappear and reappear during gameplay.
PR:
capture

Master:
master

**Comment by MSuih** [comment]
RDR no longer locks up the whole emulator for AMD cards, you can get past the title screen and into the game now. Still tends to desync and crash withing the first 20 seconds of gameplay, but at least there's some progress.

**Comment by nitrohigito** [comment]
After fighting my way through #4974, now even with the optimal settings (that work on master) and caches built, GoW: Collection managed to regress in a third way now: it just completely crashes after loading into GoW 2.

Logs:
[gowc_crash.zip](https://github.com/RPCS3/rpcs3/files/2283226/gowc_crash.zip)

**Comment by pauls-gh** [comment]
I noticed last month when I was experimenting with zcull that the zcull sample report_to_main_memory does not work in RPCS3.  It does not work with this PR either (build rpcs3-v0.0.5-0a30c563_win64).

@kd-11 - maybe you could take a look at this since you are currently improving zcull.  If you prefer, I can open a new issue...let me know.

**Comment by marosis** [comment]
How i see that pictures, in every picture is lower framerate over 2-3 fps

**Comment by sufianahmed2007** [comment]
Tekken tag 2 also got graphical errors in this PR like in some stages there is a green screen and in some stages characters are not rendered properly  and in master build it works fine but there is a fps boost in this PR 
Gameplay is very smooth and I tested using both SPU LLVM and SPU ASMJIT.
Hope I m helping 
And thanks developers

**Comment by Xcedf** [comment]
Among my games i've found GoW HD and Ninja Gaiden 3 demo regressed graphicaly the same way as on the screens above. found out both regressed from 23c74a3ad

**Comment by toccata10** [comment]
i7 8700k, r9 fury, archlinux: there's a blue color on some games
Soulcalibur V:
selection_001
Master:
selection_004
UMVC3:
selection_002
selection_003

**Comment by Dokman** [comment]
tested i am having the same issue

**Comment by raveskirza** [comment]
Same with B2S. The intro menu has blue overlay. However strict rendering seems to solve it.

**Comment by UltraStars3000** [comment]
CPU: Intel(R) Core(TM) i5-6300HQ 2.30GHz
GPU: Nvidia GeForce GTX 950M

Hyperdimension Neptunia [BLES01178] is having some graphical issues with characters during dialogs. Tested with all possible settings, and none seems to fix it.
PR:
image
Master:
image

Also a strange line is appearing at the top of the screen during loadings and 3D gameplay.
image

**Comment by Xcedf** [comment]
Discovered a regression in GoW 3, sure it now looks awesome but it suffers from random hangs with this
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x3F4AF090, put=0xA4E800 x4
E {rsx::thread} RSX: Application has failed to recover, resetting FIFO queue
F {rsx::thread} class std::runtime_error thrown: [attrib buffer] Working buffer not big enough, buffer_length=402653184 allocated=395916032 requested=4428772 guard=4194304 largest_pool=4845312
(in file c:\sources\neko\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:78)
Not sure where's this actually started, but a Cronos battle is a best testcase for this, it filled with these errors

**Comment by kd-11** [comment]
Memory ordering guarantees improved, time to retest those regressions.

**Comment by DaRkL3AD3R** [comment]
RDR is now crashing on load with FIFO queue errors infinitely looping.

**Comment by Xcedf** [comment]
FIFO queue errors in GoW 3 fixed now, completed Cronos Battle without a single crash

Btw this PR seems to fixes blacked surfaces in Lost Planet 2, was unble to see this before cause it suffered from regression that was fixed

**Comment by nitrohigito** [comment]
GoW Collection's GoW 2 seems to be fixed on both backends thanks to 4ee7499; will do further/deeper testing tomorrow.

**Comment by stride21** [comment]
Infamous 2 new commit: 
infamous 2
It does show shadows but they seem to be not as dark as they should be.

Infamous 2 old commit:
prev

Battlefield: Bad Company regressed with a similar issue as RDR.

Resistance 3 issue is now fixed.

**Comment by toccata10** [comment]
UMVC3:
blue color problem solved

soul calibur v:
without wcb: works fine (no blue overlay)

With Wcb (necessary because characters are white without it): a few random freezes:
1 )on Bandai Namco screen
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x40300CC0
2) at the beginning of a training stage:
E {SPU[0x2000002] Thread (CellSpursKernel2) [0x0aab8]} SPU: GETLLAR took too long: 14
F {rsx::thread} St13runtime_error thrown: Verification failed (e=11): 
(in file /home/rpcs3/tmp/rpcs3/rpcs3/rpcs3/Emu/RSX/VK/VKCompute.h:137)

but, by trying again, I was able to launch and play more than 6 arcade stages without major problem: framerate is rather good (45 to 60fps), with only a few minor graphical glitches.

**Comment by Kravickas** [comment]
**Far cry 2**
Vulkan - crashing in loading screen to ingame (before it was loading before splashscreens) [RPCS3.log](https://github.com/RPCS3/rpcs3/files/2290364/RPCS3.log)
OGL - as master

**GTA V**
Vulkan -  looks as master, but after 30sec ingame nvidia driver crashed hard and didnt recovered - its running ms drivers now

**Comment by stride21** [comment]
Both Battlefield: Bad Company and RDR issues are now fixed.

Uncharted 2 black screens just before making it to the main menu in this PR but if I get shaders from playing on the master then try this PR with those shaders I can get ingame.

**Comment by spyropt** [comment]
@EmulationChannel That is a regression from another pr #4975

**Comment by toccata10** [comment]
@EmulationChannel : Spu block size>safe. Works fine for me on linux. Mega block size crashes the game.

**Comment by spyropt** [comment]
@toccata10 at least on a cpu without tsx and avx it wont work i tried everything
the game crashs instantly 
it had regressed before because it would hang on fmv showing just a faint image
but now its an instant crash after pr 4975

**Comment by incognitoh** [comment]
latest master, works fine: 
toy1

this PR- 0.0.5-e3d85ad1
toy2


Using vulkan, asmjit SPU. The black parts blink/flicker constantly.

**Comment by AniLeo** [comment]
Removing comments regarding regressions from another PRs. Always test master build and PR build before submitting a report to avoid submitting false reports.

**Comment by vietnam13231** [comment]
Those weird rectangles on the left side of the Infamous are gone, game displays itself correctly.

**Comment by Dokman** [comment]
Yes is working very good even with the face glitches are now gone, but in uncharted the drake body is glitching

**Comment by legend800** [comment]
Build for latest commit failed:  https://ci.appveyor.com/project/rpcs3/rpcs3/build/9981

**Comment by Zangetsu38** [comment]
@legend800 last build is here
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-e3d85ad1/artifacts

**Comment by legend800** [comment]
That's for the commit 2 days ago. There's 1 from yesterday that failed to build. See Commits tab. I want to make sure 1) he's aware and 2) we can test the new changes soon so this can get this merged that much sooner. ;)

**Comment by Asinin3** [comment]
Ignore the 2days ago time, that's when the commit was made, not when it was merged into the PR and built. Look at the build time on the right..

**Comment by Zangetsu38** [comment]
@legend800 ? i have linked you last build compiled for this PR, ignore 2 days, like said Asinine, corresponding date for commit, and no for pushing

**Comment by Xcedf** [comment]
Strange thing, FIFO queue errors were fixed two days ago with your last commit, but now happen again

**Comment by ErackGamer** [comment]
[Here ](https://ci.appveyor.com/project/rpcs3/rpcs3/build/artifacts)is the last build, for anyone who wants to try it

**Comment by Psycho-A** [comment]
With this PR I'm getting Runtime error with Kernelbase.dll on exit emulator.
Checked with Vulkan render and Windows 7.

**Comment by theoldsport** [comment]
Skate 3 replay editor seems to have regressed back to master behavior

**Comment by kd-11** [comment]
This PR is being rebased on top of master as master also advances.

**Comment by psplayer123** [comment]
@theoldsport i just tried the latest build rpcs3-v0.0.5-a8035ccc https://ci.appveyor.com/api/buildjobs/lpsptdn5wkxracgc/artifacts/rpcs3-v0.0.5-a8035ccc_win64.7z and Skate 3 is working perfectly fine: character creation, replay editor, free skate.
All default settings ppu llvm, spu asmjit, vulkan ... 
windows 10 , gtx 1050ti, i5-2500k.

**Comment by marcosvitali** [comment]
Soulcalibur V doesnt go ingame anymore with the last version.

image

**Comment by raveskirza** [comment]
woks perfectly fine.
image

**Comment by theoldsport** [comment]
@raveskirza you sure?
image
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2298945/RPCS3.log)

**Comment by theoldsport** [comment]
Retested with identical settings with a clean cache on the same build with identical results as my screenshot

**Comment by raveskirza** [comment]
Upload your latest rpcs3.log. Also Better continue this conversation in discord #help instead of here

**Comment by marcosvitali** [comment]
@raveskirza  the problem is in master too, 7166 is working and 7195 is not.

**Comment by EmulationChannel** [comment]
Batman: Arkham Asylum
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2299502/RPCS3.zip)

**Comment by HenningJW** [comment]
@EmulationChannel have you tested against master? I don't see a log for master. What is the error? What system do you use?

Your contributions are so often not helpful, because you are missing information and your tests are very superficial (missing comparisons with master etc.). People are making fun of you with emojis on Github and Discord, because of that.

**Comment by kd-11** [comment]
Reported regressions remaining are likely caused by other changes already merged in master. I'm merging this as-is and if there are problems remaining please open an issue tracker.

**Comment by 13xforever** [comment]
Fixes black knight in The Witch and the Hundred Knight with Write Color Buffers enabled.

<details><summary>Before</summary><p>

image

</p></details>


<details><summary>After</summary><p>

image

</p></details>
