### PR TITLE
Fix build with Qt 5.15+

### PR DESCRIPTION
**Pull request by sl1pkn07**
fix build with Qt 5.15

~~~
[ 96%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/save_data_info_dialog.cpp.o
/tmp/makepkg/sl1-rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/pad_led_settings_dialog.cpp: In member function 'void pad_led_settings_dialog::redraw_color_sample()':
/tmp/makepkg/sl1-rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/pad_led_settings_dialog.cpp:82:15: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined
   82 |  QPainterPath path;
      |               ^~~~
~~~

### CODE REVIEW

**Comment by sl1pkn07** [comment]
build ok with both, `<QtGui>` or `<QPainterPath>`, but `<QPainterPath>` seems the right include

greetings

**Comment by Nekotekina** [comment]
You typed < twice

**Comment by sl1pkn07** [comment]
oh. fixed
