### PR TITLE
Fix Clang build and other small fixes

### PR DESCRIPTION
**Pull request by oltolm**
1. I fixed the Clang build.
1. I removed what I think is an unnecessary `ptrtoint` in `rpcs3/Emu/Cell/PPUTranslator.cpp`. I am not 100% sure that it's correct, but I tested a small LLVM IR snippet and it didn't make a difference. The ASM code was the same.
1. I also changed the definition of `prefetch_write` from `return __builtin_prefetch(ptr, 1, 0);` to `return __builtin_prefetch(ptr, 1, 3);` because that's how `_m_prefetchw` is defined in GCC.

### CODE REVIEW

**Comment by Megamouse** [comment]
The clang builds are working fine.
I'm not sure why you say they are not

**Comment by oltolm** [comment]
Without the fix I get a lot of these errors
```
ld.lld: error: undefined symbol: fmt::throw_exception<char, 51ull>::~throw_exception()
>>> referenced by C:/src/rpcs3/Utilities/Thread.cpp
>>>               librpcs3_emu.a(Thread.cpp.obj)

ld.lld: error: undefined symbol: fmt::throw_exception<char, 27ull, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::~throw_exception()
>>> referenced by C:/src/rpcs3/rpcs3/Emu/System.cpp
>>>               librpcs3_emu.a(System.cpp.obj)
```
I build with Clang 21.1.5. What version does the CI use?

**Comment by oltolm** [comment]
I know why it does not happen in CI. It's because I build in debug mode. It does not happen in release mode, probably because it's optimized away as unused code.

**Comment by qurious-pixel** [comment]
Please unbreak the FreeBSD builds.

```
#if defined(__FreeBSD__)
    [[noreturn]] ~throw_exception();
#endif 
```

**Comment by oltolm** [comment]
What error do you get?

**Comment by qurious-pixel** [comment]
basically return cannot be empty. so i did manually fix the first ~100 calls that leave return empty. 
```
  In file included from /home/runner/work/rpcs3/rpcs3/rpcs3/util/emu_utils.cpp:5:
  /home/runner/work/rpcs3/rpcs3/rpcs3/Emu/../Emu/Cell/PPUDisAsm.h:29:2: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
     29 |         }
        |         ^
  In file included from /home/runner/work/rpcs3/rpcs3/rpcs3/util/emu_utils.cpp:7:
  /home/runner/work/rpcs3/rpcs3/rpcs3/Emu/../Emu/Cell/SPUThread.h:557:2: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
    557 |         }
        |         ^
  2 errors generated.
  [301/932] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/System.cpp.o
  FAILED: [code=1] rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/System.cpp.o 
```
Directly from the CI. If you define a proper return after throwing an error, it will continue until the next. This happens hundred of times throughout the code.
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Cell/PPUDisAsm.h#L19-L29
so, adding a proper return will succeed.
```
	constexpr const char* get_partial_BI_field(u32 bi)
	{
		switch (bi % 4)
		{
		case 0x0: return "lt";
		case 0x1: return "gt";
		case 0x2: return "eq";
		case 0x3: return "so";
		default: fmt::throw_exception("Unreachable");
		}
		return nullptr;
	}
```

```
	//Slice 0 or 1
	u8 checkSliceRounding(u8 slice) const
	{
		switch(slice)
		{
		case 0:
			return this->_u32[3] >> 8 & 0x3;

		case 1:
			return this->_u32[3] >> 10 & 0x3;

		default:
			fmt::throw_exception("Unexpected slice value (%d)", slice);
		}
		return nullptr;
	}

```

**Comment by elad335** [comment]
Maybe fixing it hundreds of times is not actually a bad option.

**Comment by qurious-pixel** [comment]
> Maybe fixing it hundreds of times is not actually a bad option.

it is not. but some of it requires actual definitions. 

```
	{
		switch (m_layout)
		{
		case audio_channel_layout::automatic:        break;
		case audio_channel_layout::mono:             return CUBEB_LAYOUT_MONO;
		case audio_channel_layout::stereo:           return CUBEB_LAYOUT_STEREO;
		case audio_channel_layout::stereo_lfe:       return CUBEB_LAYOUT_STEREO_LFE;
		case audio_channel_layout::quadraphonic:     return CUBEB_LAYOUT_QUAD;
		case audio_channel_layout::quadraphonic_lfe: return CUBEB_LAYOUT_QUAD_LFE;
		case audio_channel_layout::surround_5_1:     return CUBEB_LAYOUT_3F2_LFE;
		case audio_channel_layout::surround_7_1:     return CUBEB_LAYOUT_3F4_LFE;
		}

		fmt::throw_exception("Invalid audio layout %d", static_cast<u32>(m_layout));
		return CUBEB_LAYOUT_UNDEFINED;
	}();
```
defining the return for CUBEB and defining non-values 
```
cfg::string& mouse_config::get_button(int code)
{
	switch (code)
	{
	case CELL_MOUSE_BUTTON_1: return mouse_button_1;
	case CELL_MOUSE_BUTTON_2: return mouse_button_2;
	case CELL_MOUSE_BUTTON_3: return mouse_button_3;
	case CELL_MOUSE_BUTTON_4: return mouse_button_4;
	case CELL_MOUSE_BUTTON_5: return mouse_button_5;
	case CELL_MOUSE_BUTTON_6: return mouse_button_6;
	case CELL_MOUSE_BUTTON_7: return mouse_button_7;
	case CELL_MOUSE_BUTTON_8: return mouse_button_8;
	default: fmt::throw_exception("Invalid code %d", code);
	}
}
```

There are 184 instances to define.

**Comment by elad335** [comment]
You can add for example:

```
template <typename T> requires (std::is_default_constructible_v<T> && std::is_move_constructible_v<T>>
operator T() const noexcept
{
    return T();
}

template <typename T> requires (std::is_lvalue_reference_v<T&&>>
operator T&&() const noexcept
{
    return *std::add_pointer_t<std::remove_reference_t<<T&&>>();
}
```
to `struct throw_exception`.

And have stuff like this:

```
cfg::string& mouse_config::get_button(int code)
{
	switch (code)
	{
	case CELL_MOUSE_BUTTON_1: return mouse_button_1;
	case CELL_MOUSE_BUTTON_2: return mouse_button_2;
	case CELL_MOUSE_BUTTON_3: return mouse_button_3;
	case CELL_MOUSE_BUTTON_4: return mouse_button_4;
	case CELL_MOUSE_BUTTON_5: return mouse_button_5;
	case CELL_MOUSE_BUTTON_6: return mouse_button_6;
	case CELL_MOUSE_BUTTON_7: return mouse_button_7;
	case CELL_MOUSE_BUTTON_8: return mouse_button_8;
	default: return fmt::throw_exception("Invalid code %d", code);
	}
}
```
