### ISSUE TITLE
Can't compile in clang - Gentoo 64 - chosen constructor is explicit in copy-initialization

### ISSUE THREAD

**Issue by latot** [RPCS3/rpcs3#2245]
Hi all, well trying to compile this again i found this:

```
make
[  4%] Built target png16_static
[  4%] Generating something_that_never_exists
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- GIT_VERSION: 4784-9e84804e
[  4%] Built target GitVersion
[  6%] Built target rsx_decompiler
[  7%] Built target shader_code
Scanning dependencies of target rpcs3
[  7%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Emu/IdManager.cpp.o
/home/pipe/Documentos/git/rpcs3/rpcs3/Emu/IdManager.cpp:87:51: error: chosen constructor is explicit in
      copy-initialization
        g_map.resize(id_manager::typeinfo::get().size(), {});
                                                         ^~
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/unordered_map.h:139:7: note: constructor
      declared here
      unordered_map(size_type __n = 10,
      ^
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:693:54: note: passing argument
      to parameter '__x' here
      resize(size_type __new_size, const value_type& __x)
                                                     ^
1 error generated.
rpcs3/CMakeFiles/rpcs3.dir/build.make:4251: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/Emu/IdManager.cpp.o' failed
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/IdManager.cpp.o] Error 1
CMakeFiles/Makefile2:270: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Notes, i'm using clang-3.9, over gcc-5.4 seems pass this part.

Thx. Cya.

**Comment by AniLeo** [comment]
#2236
Please build with a compatible gcc version and try again

**Comment by latot** [comment]
Hi, this different, this is compiled with clang 3.9 as i say above, and as a note that part pass when i compile with gcc-5.4, here the issue is with clang.

**Comment by AniLeo** [comment]
_/usr/lib/**gcc**/x86_64-pc-linux-gnu/**4.9.3**/include/**g++-v4**/_
It appears you're using **gcc 4.9.3** to compile

**Comment by latot** [comment]
Hi, sadly i can't compile with gcc-4.9, it fails in other part as i describe in other issue, and why is showing that i don't have idea, only to describe what i'm doing, to choose clang i'm changing the direction of compile to clang instead of gcc (to clang) and g++ (to clang++), i'm doing this right or i miss something?

**Comment by kirbyfan64** [comment]
Clang uses g++'s standard library files. You could try installing libc++ and passing `-stdlib=libc++` to Clang.

**Comment by latot** [comment]
Hi, in gentoo we always have all dev-packages installed, and i try your recommendation but sadly the same problem....

**Comment by hcorion** [comment]
Closing because was attempting to use ancient gcc 4.9.3 headers.
