### ISSUE TITLE
Build: Add support for OpenCV 5.0.0

### ISSUE THREAD

**Issue by BriellaBugs** [RPCS3/rpcs3#19000]
```
rpcs3/Input/ps_move_tracker.cpp:311:6: error: no member named 'approxPolyDP' in namespace 'cv'
  311 |         cv::approxPolyDP(contour, approx, 0.01 * cv::arcLength(contour, true), true);
      |             ^~~~~~~~~~~~
rpcs3/Input/ps_move_tracker.cpp:311:47: error: no member named 'arcLength' in namespace 'cv'
  311 |         cv::approxPolyDP(contour, approx, 0.01 * cv::arcLength(contour, true), true);
      |                                                      ^~~~~~~~~
rpcs3/Input/ps_move_tracker.cpp:314:30: error: no member named 'contourArea' in namespace 'cv'
  314 |         area = static_cast<f32>(cv::contourArea(contour));
      |                                     ^~~~~~~~~~~
rpcs3/Input/ps_move_tracker.cpp:319:6: error: no member named 'minEnclosingCircle' in namespace 'cv'
  319 |         cv::minEnclosingCircle(contour, center, radius);
      |             ^~~~~~~~~~~~~~~~~~
rpcs3/Input/ps_move_tracker.cpp:456:7: error: no member named 'minEnclosingCircle' in namespace 'cv'
  456 |                 cv::minEnclosingCircle(contour, center, radius);
      |                     ^~~~~~~~~~~~~~~~~~

```

These are the errors that show up when trying to build with OpenCV 5.0.0

**Comment by hcorion** [comment]
Fixed in https://github.com/RPCS3/rpcs3/commit/5c90bf5865b5f820231c0af87955bdfab28f0c14

**Comment by BriellaBugs** [comment]
Ah glad to see it was a simple fix, thanks @hcorion !
