### PR TITLE
RSX: Reimplement the vertex processing stage; Minor fixes

### PR DESCRIPTION
**Pull request by kd-11**
- This set reimplements the RSX driver side of the vertex processing stage. Vertex attribute data is no longer processed on the CPU freeing up resources otherwise used up dealing with this task. This moves a lot of work over GPU side and slow iGPUs might become a bottleneck.
Due to the increased complexity of the shaders, a preloaded shader cache system is also included to allow the shader compilation and linking to happen outside of gameplay. This fixes the hitching and stuttering ingame at the cost of longer loading times. The cache can be deleted from the context menu.
- Also included is a partial rewrite of the vulkan renderer to take advantage of parallel frame processing. The frame queue is now double-buffered improving performance and reducing stutter.
- Also includes several minor fixes that should fix Ni No Kuni on both vulkan and opengl
- Properly implement VSync control when using openGL (at least under windows)

I am aware that intel chips are missing output in some games and will continue investigating the matter. In the meantime, any other issues encountered with AMD or Nvidia GPUs should be tracked here.

### CODE REVIEW

**Comment by kamer1337** [comment]
Reduced performance in Tony Hawk's Project 8, fps drops to 0.5 a lot, stutters really bad for me

**Comment by SakataGintokiYT** [comment]
@kamer1337
Delete data folder

**Comment by kamer1337** [comment]
@SakataGintokiYT i did

**Comment by kd-11** [comment]
You have to let the shader cache build first. WIthout it the graphics drivers sometimes struggle linking the large shaders. Its not a bug.

**Comment by Illynir** [comment]
Huge regression on Dragon quest Builders (BJLM61311), i told you that already but it's official now. :)

Many objects, item, trees are invisible now, they are present but invisible.

dq

Game is unplayable now. Performance are good however.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1218318/RPCS3.zip)

**Comment by Xcedf** [comment]
Played Dante's Inferno for two levels flawless 60 fps on my 6700k, other games are speeded up too
another great improvement

**Comment by Xcedf** [comment]
Some games like Bionic Commando which had horrible frame-drops on master builds after having shader cache running pretty much smooth, another improvement RDR no longer seems to have random geomtery artifacts

**Comment by Luffykun007** [comment]
I'm having this mistake now in Ni No Kuni

E {rsx::thread} HLE: Getting the real address failed. (addr=0x1da3900)
E {rsx::thread} RSX: Invalid FIFO queue get/put registers found, get=0x1DA3900, put=0x41FD40

**Comment by SaltyCucumber** [comment]
Don't know if placebo or not, but some parts of Demon's souls runs smoother.
Though there was once a strange glitch where all the ground textures were dark green, I warped back and forth from nexus and it was gone. After more running around if finally froze during loading. I'll add the log just in case.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1218390/RPCS3.zip)

**Comment by kamer1337** [comment]
@kd-11 game stutters every i first time visit the spot then it run smooth but it happens every run

**Comment by MarcoEstevez** [comment]
Firstable, congrats, you @kd-11 did an amazing job, I tested just 2 or 3 weeks ago Rune Factory Oceans and I was lucky if It reached 7-12 fps on the fist intro-tutorial battle, few days later with another commit, game almost reached 20-25 fps, enough for enjoying this low pacing game, but with current commit its playing full speed all the time, seriously unbeliebable.

hats off to you  :-D

**Comment by kamer1337** [comment]
@bobthecooldad if it doesnt crash or anything just stuck then you have to wait minute or more for the first time run

**Comment by Illynir** [comment]
@Luffykun007 Same here, but only with Vulkan. On OGL it's good.

**Comment by bobthecooldad** [comment]
been 15-20 ish minutes with no movement on first load of the game

**Comment by JusicP** [comment]
@Luffykun007 Same thing with Battlefield 4 on OpenGL and Vulkan
[BF4 VK.zip](https://github.com/RPCS3/rpcs3/files/1218447/BF4.VK.zip)
[BF4 GL.zip](https://github.com/RPCS3/rpcs3/files/1218443/BF4.GL.zip)

**Comment by Luffykun007** [comment]
@illinir The same problem with the rsx reported above with the Vulkan api also happens in Opengl!

capturar1

**Comment by Illynir** [comment]
Oh, ok. :(

**Comment by Luffykun007** [comment]
Error also happens in Ni No Kuni [NPUB30932]

capturar2

**Comment by Redfry** [comment]
@Luffykun007 I have this problem too, but on disk version of game

**Comment by kd-11** [comment]
If you were getting stutter every time even after first run, please retest.
@SaltyCucumber DeS has had that issue for a long time. You can watch lobosjr's emulator run and you'll see the same bug. I've experienced more drastic versions of it including the whole character model being green or red

**Comment by kamer1337** [comment]
latest commit fixed stuttering

**Comment by kd-11** [comment]
@Illynir I need the opengl renderdoc trace showing before and after

**Comment by kamer1337** [comment]
Vulcan regression on Unreal Engine 3 games, randomly crash the emulator

tony hawk's pro skater hd
tony hawk's pro skater 5

**Comment by kamer1337** [comment]
Unreal Engine 3 games like to crash the emulator on this build with vulkan

tony hawk pro skater hd and tony hawk pro skater 5

**Comment by kamer1337** [comment]
broken config in 31a9988 cant open, crash emu

**Comment by kamer1337** [comment]
it uses 100% of my ram and goes up 

wtf

**Comment by Illynir** [comment]
@kamer1337 You have a nvidia card ? If yes, it's a bug of high consumption ram with the driver Nvidia. CEMU has the same problem.

**Comment by kamer1337** [comment]
yes, i have nvidia

**Comment by Illynir** [comment]
I thought so... So no solution for that, it's a Nvidia driver bug. :-/

**Comment by tabnk** [comment]
Tested Virtua Fighter 5 Final Slowdown. Amazing huge speed up from 61 to 120 fps. :) Well done.

**Comment by Asinin3** [comment]
Vulkan crashes for me in 0.0.3-5653 after 1-15seconds graphics look near-perfect now though, only posting because I saw other users not having this issue with 5651 and up.
[RPCS3_Ni_No_Kuni_Vulkan_Freeze.zip](https://github.com/RPCS3/rpcs3/files/1219465/RPCS3_Ni_No_Kuni_Vulkan_Freeze.zip)

I am using windows 10 (so it shouldn't be related to the win7 hang in DeS)
CPU: R7 1700 OCed @ 3.9ghz
GPU: GTX 1080ti

**Comment by zminhquanz** [comment]
Catherine perfomance regression ( Core 2 Quad ) for this request

**Comment by Dokman** [comment]
@zminhquanz This is a high performance update, and it requieres a good graphics card

**Comment by zminhquanz** [comment]
@Dokman but i use GTX 950

**Comment by Asinin3** [comment]
@zminhquanz Come to the Discord channel and ask in #help channel and we can see if your settings are optimal. I don't think Kd-11 is asking about performance or there would be hundreds of posts.

**Comment by Redfry** [comment]
@Asinin3 yes, i have this problem too, but on OGL Ni no Kuni works very good stable 20fps sometimes drop to 19 and up to 24 in start location.
I am using win7
CPU I5 4460
GPU R7 250X

**Comment by Asinin3** [comment]
@Redfry Does it freeze very quickly? or only rarely? It could just be this issue: https://github.com/RPCS3/rpcs3/issues/3136

**Comment by OverlordCW** [comment]
RDR GOTY [BLES01294]
F {rsx::thread} class std::runtime_error thrown: Unknown magnify filter 0x0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:631)

F {rsx::thread} class std::runtime_error thrown: Working buffer not big enough, buffer_length=268435456 allocated=266424320 requested=2097152 guard=65536 largest_pool=3140096
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:74)

F {rsx::thread} class std::runtime_error thrown: Unknown stencil op 0x8180
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:705)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1219595/RPCS3.zip)

**Comment by Redfry** [comment]
@Asinin3 fps drop to 15 and freezes 1-2 times every 1-2 sec

**Comment by Asinin3** [comment]
@Redfry I'm not talking about stutter for a few seconds, that is completely normal. This build generates a shader cache now and that's why it's stuttering. I was talking about a complete and total freeze, basically a crash but the game audio keeps playing and you don't get an error window.

**Comment by bjakja** [comment]
@Dokman what grapics card I need to get high performance? GTX 1070 is enough?

**Comment by Asinin3** [comment]
@bjaka This is not the place to ask but yes that card is more than enough all you need is a card that supports vulkan basically. (delete your comment once you read this, lets keep this comment section clean, if you want advice or help ask on discord #help channel.)

**Comment by Redfry** [comment]
I'm testing build's in start location and on this build total freezes gone, but maybe they can happen in another location.
Now, in start location, i can play without any errors and total freezes

**Comment by Asinin3** [comment]
@Redfry Please read the comment I posted the stutters are completely normal, then delete them to keep this clean.

**Comment by kd-11** [comment]
Freezing with corrupt heap might be just from increased framerate. Test on master with null renderer and it might still happen. Bugs introduced by this pr would be driver crashes amd...dll or nvoglv..dll. That or missing/corrupt graphics. No part of this pr changes writes to emulated host memory.

**Comment by Asinin3** [comment]
@kd-11 Confirmed, just tried with Null renderer and when I loaded save it froze within 20seconds with the same error.

**Comment by kamer1337** [comment]
is it possible to include disable shaders cache option? due to nvidia bug and high ram usage.

**Comment by Dokman** [comment]
@kamer1337 w8 until nvidia fix it

**Comment by SmileX-san** [comment]
@kd-11 Please include an option to disable shader cache, because that stuttering on the 1st run (also followed by video/audio desync) spoils the whole gameplay. I tested Catherine. On master build it runs flawlessly on my configuration (Core i7-6700K + GTX 1070), but on this PR shader cache stuttering is very annoying. It happens everytime I enter a new location or a new cutscene and makes shader cache system absolutely unwanted for my configuration. That's why I'm asking to include an option to disable shader cache.

**Comment by Dokman** [comment]
@SmileX-san w8 until nvidia want to fix the ram bug or use more ram

**Comment by SmileX-san** [comment]
@Dokman Ram usage is not an issue for me. I have 32 GB of RAM. The real issue is the increased complexity of the shaders in this PR followed by a shader cache system implementation. It is a probable solution for some games which run slow at the moment. But it also spoils the games that ran flawlessly before.

**Comment by SakataGintokiYT** [comment]
@kd-11 
@Illynir 

**[Dragon Quest Builders  ]**
**[Master-RenderDoc:](https://mega.nz/#!UAgmRAwS!skWTJ0svVw99DOrq6YDPtVzbDpwQlTZcpzOc9kn-h84)**
**[Vertex_rewrite-RenderDoc:](https://mega.nz/#!0RgGkDJK!3oJF_NgXUTKhXunTvRmaQMlkl8zVytvt0HksTdjvd_8)**

**Comment by Zangetsu38** [comment]
@SakataGintokiYT i have already send this directly ^^

**Comment by Illynir** [comment]
@SakataGintokiYT Thx. ;)

**Comment by tabnk** [comment]
Speed improved greatly for Outrun online arcade. :).

**Comment by kd-11** [comment]
Dragon Quest Builders should be fixed now hopefully.

**Comment by Illynir** [comment]
I will test now. ;)

**Comment by Illynir** [comment]
Sorry KD but it's worse now. Flickering anywhere AND invisible object.

image

**Comment by kd-11** [comment]
Last commit was buggy. Retest.

**Comment by Luffykun007** [comment]
Oh shit!

capturar

**Comment by SakataGintokiYT** [comment]
@kd-11 
Fixed
bez tytulu

**Comment by Illynir** [comment]
Yes it's fixed.

**Comment by OverlordCW** [comment]
@kd-11 Does your change to vsync mean we will get screen tearing if fps < refresh rate?

**Comment by tabnk** [comment]
RPCS3 with **AMD GPU** - Game Tested Virtua Fighter 5 - Final Showdown

RPCS3 stuck at this screen. HDD generate extra 20GB storage. 

Btw, It is fine on another system with Nvidia GPU.

image


Error Log:
U {PPU[0x1000000] Thread (main_thread) [0x0037b5b8]} cellNetCtl TODO: cellNetCtlAddHandler(handler=*0x892f00, arg=*0x0, hid=*0xf4e69c)
U {PPU[0x1000000] Thread (main_thread) [0x0037b604]} sceNp TODO: sceNpManagerRegisterCallback(callback=*0x893478, arg=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x0037b63c]} sceNp TODO: sceNpBasicRegisterContextSensitiveHandler
U {PPU[0x1000000] Thread (main_thread) [0x0037b6dc]} sceNp2 TODO: sceNpMatching2Init2(poolsize=0x0, priority=0, param=*0x0)
U {PPU[0x1000000] Thread (main_thread) [0x0040f140]} sys_spu TODO: Unimplemented SPU Thread options (0x2)
S {SPU[0x2000000] Thread (CriSr thread)} SPU: SPU Database initialized...
S {SPU[0x2000000] Thread (CriSr thread)} SPU: SPU Recompiler (ASMJIT) created...
U {PPU[0x1000013] Thread (thr_bootcheck) [0x0037dbe8]} sceNpTrophy TODO: sceNpTrophyGetRequiredDiskSpace(context=0x1, handle=0x1, reqspace=*0xd00bbb20, options=0x0)
E {PPU[0x1000013] Thread (thr_bootcheck) [0x0037dc10]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0x8932a0, arg=*0xf51e60, options=0x1)
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000002] Thread (_cellsurMixerMain) [0x00444db0]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [1]
E {PPU[0x1000002] Thread (_cellsurMixerMain) [0x004e3c50]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [1]
E {PPU[0x1000002] Thread (_cellsurMixerMain) [0x004e3ce8]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [2]
E {PPU[0x1000002] Thread (_cellsurMixerMain) [0x004e3c50]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [2]
E {PPU[0x1000002] Thread (_cellsurMixerMain) [0x004e3ce8]} 'sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]
E {PPU[0x1000002] Thread (_cellsurMixerMain) [0x004e3c50]} 'sys_lwmutex_unlock' failed with 0x80010009 : CELL_EPERM [3]
E {rsx::thread} RSX: Program end before buffer end.

**Comment by AniLeo** [comment]
Don't copy pasta console output, attach a log

**Comment by kd-11** [comment]
@tabnk right click game icon and select delete shader cache. Your cache data was corrupted by a possible crash. The cache size should be less than 5mb even with 3k+ shaders

**Comment by ScorchEmber256** [comment]
This commit is causing odd texture flickering every 5 seconds. Tested with KH2.5 and Spyro DOTD

**Comment by tabnk** [comment]
@kd-11 It fixed the issue. Tks

**Comment by Uramekus** [comment]
Hey KD-11, i see you made a patch with workarounds for intel GPUs, would you please see if this behavior is needed on BOTH linux and windows? drivers are so much different and vendor_INTEL = true; for someone that has not seen al the code implies to me you are not seeing if its intel windows or intel linux, maybe this haxx wont help intel on linux.

**Comment by kd-11** [comment]
@Uramekus Its not a hack and shouldnt break anything. Its ineffecient, sure, but shouldn't cause problems if the linux driver works properly. My iGP doesnt work properly when using intel as my display so someone will have to test it. Just comment out the vendor_INTEL check and see what happens on linux. If linux isnt affected we can wrap the check to windows only.

**Comment by Ru4slan** [comment]
Game Hard Corps Uprising now works on OpenGL 3.3

**Comment by jjsat** [comment]
This PR breaks the immediate index buffer rendering in Wolfenstein.

vertex_rewrite:
clipboard01

On current master:
clipboard02

**Comment by Xcedf** [comment]
Condemned 2 has a severe slowdowns even with precompiled cache on OGL, i believe it started with https://github.com/kd-11/rpcs3/commit/5d8ef847af3819e60e45afe79e562ab6cf71aae0 
can't say for sure cause it has sahder compilation errors and next 3-5 commits are fixing it

**Comment by kd-11** [comment]
@jjsat Thanks for testing. I'll open a tracker for immediate rendering after merging this since its getting too large to effectively track regresssions. Its originally 54 commits.
@Xcedf  How is it slower? stuttering or smooth lower fps? Depending on how frame-to-frame timings vary it could be anything. The commit you pointed to moves load to the GPU which makes every other game faster so its wierd that its slower for you. You could monitor resource usage using GPU-z, maybe there is a vram memory leak somewhere although its unlikely

**Comment by kd-11** [comment]
Actually the immediate mode rendering issue looks simple enough. I'll squeeze in the fix before merge.

**Comment by Xcedf** [comment]
@kd-11 It's stutterring as hell, in the rare moments if it's not stuttering it's actually faster than master, and the game itself has wierd texture flickering problems even on master, look's like this PR stutters every time when it happens

**Comment by danilaml** [comment]
Can confirm very noticeable desync on initial run in Catherine. It's obviously fine on the second run,  but it's not really fun the 1st time) Is it possible to precompile shaders beforehand? Also, you've probably already seen/read it but here is a nice article from doplhin-emu on the issue: https://dolphin-emu.org/blog/2017/07/30/ubershaders/

**Comment by kd-11** [comment]
ubershaders means implementing a GPU microcode interpreter to run on the GPU. Its nice, but it will be a while before thats done if at all. We cant know where to get the shader data or how they will be used before they are used, so thats a problem. Vulkan has heavier compilation penalties than openGL so if all else fails, fall back to GL. It also has less state permitations than vulkan, and performance is pretty much identical now anyway.

**Comment by danilaml** [comment]
@kd-11 well. maybe something like Asynchronous Shader Compilation would be a good enough workaround for the time being (though no idea how hard it would be to implement in rpcs3), since shader compiling/loading doesn't really stall all the threads correctly in the current implementation either, i.e. it looks like audio threads just continue without much problem while the graphics stutter, creating nasty desyncs in some cutscenes, and that's troubling since it's probably the only place where a lot of new shaders might be introduced as gameplay parts would be pretty much covered after completing first few stages.

**Comment by kd-11** [comment]
Its not so simple. The problem is at the link stage, which will be done by the driver synchronously. The compile step isnt so bad from my measurements. The only way around it is to simiplify shader design (not an option) or lower the number of shader permutations. I'm looking into the latter but the shader pipeline is in a bad state right now.

**Comment by kd-11** [comment]
@jjsat I fixed the problem with wolfenstein here https://github.com/RPCS3/rpcs3/pull/3241. I have noticed some flickering and will continue investigating although it might have already been a problem on master.

**Comment by Luffykun007** [comment]
@ KD11- Unfortunately still freezes for me in Build # 905

capturar

**Comment by kd-11** [comment]
Read https://github.com/RPCS3/rpcs3/pull/3200#issuecomment-321956448
The issue isnt caused by the PR - it already existed before but the emulator was too slow to trigger it.

**Comment by Blacksama** [comment]
Playing persona 5 there is flickering everywhere, you see that white wall it happens every few seconds and there is a giant white wall flickering every 2-3 seconds: rendering the game a mess:

http://i.imgur.com/uVbEcPp.jpg

**Comment by Asinin3** [comment]
@Blacksama Does this happen under vulkan?

**Comment by Blacksama** [comment]
Yes Vulkan, is exactly caused by this build and the flickering was never present in any previous build, is not only the wall, the characters, the windows,the ceiling, everything flickers white/other colors at random.

The performance increase is tremendous though, is pretty much perfect speed. although my computer was running it at nearly  perfect speed before. I will post the log once I arrive from work which is in 6-8 hours, sorry about that. I started used a previous build and the flicker went away.

**Comment by Blacksama** [comment]
The log also a few Screenshots, btw I did not go past intro as the very first screen (before load) 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1232958/RPCS3.zip)
has the flickering bug let me know if you need anything else.

**Comment by Asinin3** [comment]
@Blacksama Try Preferred SPU threads = 2 or 3 if that doesn't fix it try using a 1280x720 resolution with the aspect ratio set to 16:9.

**Comment by Blacksama** [comment]
SPU thread 2 and 3, did nothing flickering still present.
Res 1280x720 and aspect ratio 16:9 murdered the performance, did nothing flickering still present.

In the build previous to this, flickering is not present.

**Comment by Kravickas** [comment]
F 0:01:25.818559 {rsx::thread} class std::runtime_error thrown: Working buffer not big enough, buffer_length=268435456 allocated=12971008 requested=2539170208 guard=65536 largest_pool=91648
(in file c:\rpcs3\rpcs3\emu\rsx\d3d12\../Common/ring_buffer_helper.h:74)

Using vulkan
RDR GOTY
[rpcs3-v0.0.3-2017-08-17-8b303feb_win64.zip](https://github.com/RPCS3/rpcs3/files/1233216/rpcs3-v0.0.3-2017-08-17-8b303feb_win64.zip)

**Comment by BreakShadow0504** [comment]
The shader cache is KILLING Miku Project Diva(any of the series, F, F2nd, Dreamy Theater).
S {rsx::thread} RSX: New program compiled successfully.
↑ This will slow down the game.
It's a MUG and it can't bear any slowdown.
I must watch my play for a song, from start to end, and fail once for one specific song, to properly play it next time.
EVERY new part of a newly played song will cause this slowdown and it can't be helped.
Can we have a switch that can close this cache functionality?
Thanks.

**Comment by Asinin3** [comment]
I don't see the point in adding a switch to disable shader cache yet, stick to the older builds for that game until the implementation is fixed. There is some major problems with the shader cache at the moment where it generates too many shaders for a game or repeatedly generates the same shaders over and over. When this is resolved the performance should be good again, if there is some other reason to disable the cache that can't be resolved then it may be worth the time however...

**Comment by BreakShadow0504** [comment]
@Asinin3 I get it. THX.
Any build before this PR are OK for this issue? Thanks.

**Comment by Asinin3** [comment]
@BreakShadow0504 Yeah any build before this PR won't have shader cache enabled.

**Comment by Asinin3** [comment]
@Blacksama Try updating GPU drivers, or rolling them back if you're using the latest drivers someone else has had the same issue with the new builds and updating fixed it. If it keeps happening try OpenGL.

**Comment by Sztefanol** [comment]
In Hatsune Miku:Project Diva F (BLUS31319) on vulkan depending on scene every third or fifth or so frame is dropped. I was testing on one song to ensure no new shaders are compiled. CPU usage at ~30-40% and GPU at ~15-20% at all times. Frame drops aren't reflected on FPS counter.
No frame drops prior to this build and newer builds don't help either. OpenGL performance is about the same on any build but it's not buttersmooth like on vulkan prior to this build.

**Comment by kd-11** [comment]
If you use a variable rate monitor, you'll notice the frame isnt actually dropped, its submitted at the 'wrong' time due to lack of framepacing. Framepacing requires a FIFO queue managed by rpcs3 since we already manage the driver's FIFO queue and write to the back and front surfaces directly. This would improve smoothness at the cost of increased frame latency. Before, no new frames were submitted for present asynchronously which is why the frametime metric was stable across samples.

**Comment by Muramas** [comment]
So far Persona 5 has been running really good and a lot less stuttering. I wanted to say that you have done an awesome job! Thanks for all the hard work.
