### PR TITLE
Implement a d3d12 backend

### PR DESCRIPTION
**Pull request by vlj**
This PR add a D3D12 backend for rpcs3.

The backend runs most simple elf like openGL backend does, at similar speed.
Full application compatibility is slightly worse than GL backend (Scrogger HD doesnt run for instance, Disgaea 3 doesn't either), on the other hand the performance are sometimes better (Arkedo 3), at least I didn't find an app where DX12 backend was slower. Some artifacts are also not present in DX12 (Terraria)

DX12 backend miss some texture formats support and vertex texture fetch.

I added 4 new configuration, Debug - DX12, Debug - LLVM DX12, Release - DX12 and Release - LLVM DX12 ; to build them VS 2015 and windows 10 SDK is required. However the resulting binary should work on windows 7/8/8.1 (with opengl backend obviously) but I didn't test this.

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Problem compilation error asmjit.lib not found in release dx12 llvm

**Comment by tambry** [comment]
@Zangetsu38 Yes, because you'll probably have to sync submodules and do "submodule update --init". Just wait until the conflicts are resolved and it's merged into master.

**Comment by Zangetsu38** [comment]
@tambry no, asmjit.lib exist on folder "rpcs3 DX12\libs\Release" so what this error ? hmm

**Comment by tambry** [comment]
@Zangetsu38 You'll have to consult @vlj about the problem if you want help. You'll also most likely need to provide the *full* log.

**Comment by Zangetsu38** [comment]
I find problem, rpcs3 dx12 sheach file on bad folder

**Comment by vlj** [comment]
Can you create a branch with your patch applied on it ? Here I can't apply, it says "fatal: git apply: bad git-diff - expected /dev/null on line 92"

**Comment by Zangetsu38** [comment]
hmm I not solve the problem as, besides applying the old sln and asmjit.vcxproj of yesterday is the I saw he was looking in the wrong folder.
He seeks him here .lib "libs\Release - DX12".

**Comment by Zangetsu38** [comment]
@vlj Fixed here https://gist.github.com/Zangetsu38/e60ec5db09b4dd2b3474 
It's not great but it works, the "$ (Configuration)" is problematic here

File: rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp [hunk 1]
```diff
@@ -0,0 +1,1363 @@
...
+GetGSFrameCb2 GetGSFrame = nullptr;
+
+void SetGetD3DGSFrameCallback(GetGSFrameCb2 value)
+{
+	GetGSFrame = value;
+}
+
+GarbageCollectionThread::GarbageCollectionThread()
+{
+	m_worker = std::thread([this]() {
```
Comment (Nekotekina) [inline rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp]: How this thread is terminated? I suppose it must me joined in the destructor since it captures `this`.

File: rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp [hunk 2]
```diff
@@ -0,0 +1,1363 @@
...
+		while (true)
+		{
+			std::unique_lock<std::mutex> lock(m_mutex);
```
Comment (Nekotekina) [inline rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp]: I suggest to compare the implementation with CallbackManager::Async in Callback.cpp, it's pretty similar, but avoids some potential flaws.

File: rpcs3/Gui/MainFrame.cpp [hunk 3]
```diff
@@ -474,7 +477,15 @@ void MainFrame::Config(wxCommandEvent& WXUNUSED(event))
 
 	cbox_gs_render->Append("Null");
 	cbox_gs_render->Append("OpenGL");
-	//cbox_gs_render->Append("Software");
+#if defined(DX12_SUPPORT)
+	cbox_gs_render->Append("DirectX 12");
+#endif
+
+	cbox_gs_d3d_adaptater->Append("WARP");
```
Comment (danilaml) [inline rpcs3/Gui/MainFrame.cpp]: shouldn't this box be ifdefed too?

**Comment by vlj** [comment]
Rebased + using same way as nekoteki for Producer/consumer thread pattern.

**Comment by vlj** [comment]
I reworked the garbagecollection thread

**Comment by vlj** [comment]
I added a mutex in the dtor

**Comment by Nekotekina** [comment]
Seems OK for me, but now I cannot build Release. It says that it cannot open input file libOpenAL32.dll.a

**Comment by vlj** [comment]
Should work now, I tested Release, Release - LLVM, Release - DX12, Release - LLVM DX12, Debug and Debug - DX12. I'm currently building Debug - LLVM DX12 but it takes time (llvm is really huge in debug mode)

**Comment by vlj** [comment]
Debug - LLVM and Debug - LLVM DX12 also build.
