### PR TITLE
Fix build with Qt 6.10

### LINKED ISSUE #17570: Unable to build with Qt 6.10
### Quick summary

I'm using the AUR package of RPCS3. Yesterday Qt got updated from 6.9 to 6.10. Since then I'm unable to compile the project.

### Details

I checked the changelog of Qt 6.10 and they added more restrictions on the use of private modules.
> Usage of a private Qt module Foo now requires a call to find_package(Qt6 COMPONENTS FooPrivate) to make the Qt6::FooPrivate target available.

I added `GuiPrivate` to `find_package()` and `Qt6::GuiPrivate` to `target_link_libraries()` in 3rdparty/qt6.cmake which resolved the compiler error.

### Attach a log file

```
/home/erik/.cache/paru/clone/rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/gs_frame.cpp:42:10: fatal error: 'qpa/qplatformnativeinterface.h' file not found
   42 | #include <qpa/qplatformnativeinterface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/build.make:663: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/gs_frame.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3292: rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'rpcs3-git-0.0.37.r17986.68d2573344-1':
error: packages failed to build: rpcs3-git-0.0.37.r17986.68d2573344-1
```

### Attach capture files for visual issues

_No response_

### System configuration

_No response_

### Other details

_No response_

### PR DESCRIPTION
**Pull request by engdyn**
Qt 6.10 now requires find_package() for private modules. This fixes #17570

### CODE REVIEW

**Comment by regularhunter** [comment]
Using your proposed patch I still get build fails on openSUSE Tumbleweed. The following patch successfully compiles for me (though that doesn't mean it is correct).

```
diff --git a/3rdparty/qt6.cmake b/3rdparty/qt6.cmake
index ef89bda..bda135a 100644
--- a/3rdparty/qt6.cmake
+++ b/3rdparty/qt6.cmake
@@ -6,12 +6,12 @@ find_package(Qt6 ${QT_MIN_VER} CONFIG COMPONENTS Widgets Concurrent Multimedia M
 if(WIN32)
 	target_link_libraries(3rdparty_qt6 INTERFACE Qt6::Widgets Qt6::Concurrent Qt6::Multimedia Qt6::MultimediaWidgets Qt6::Svg Qt6::SvgWidgets)
 else()
-	find_package(Qt6 ${QT_MIN_VER} COMPONENTS DBus Gui)
+	find_package(Qt6 ${QT_MIN_VER} COMPONENTS DBus GuiPrivate)
 	if(Qt6DBus_FOUND)
-		target_link_libraries(3rdparty_qt6 INTERFACE Qt6::Widgets Qt6::DBus Qt6::Concurrent Qt6::Multimedia Qt6::MultimediaWidgets Qt6::Svg Qt6::SvgWidgets)
+		target_link_libraries(3rdparty_qt6 INTERFACE Qt6::Widgets Qt6::DBus Qt6::Concurrent Qt6::GuiPrivate Qt6::Multimedia Qt6::MultimediaWidgets Qt6::Svg Qt6::SvgWidgets)
 		target_compile_definitions(3rdparty_qt6 INTERFACE -DHAVE_QTDBUS)
 	else()
-		target_link_libraries(3rdparty_qt6 INTERFACE Qt6::Widgets Qt6::Concurrent Qt6::Multimedia Qt6::MultimediaWidgets Qt6::Svg Qt6::SvgWidgets)
+		target_link_libraries(3rdparty_qt6 INTERFACE Qt6::Widgets Qt6::Concurrent Qt6::GuiPrivate Qt6::Multimedia Qt6::MultimediaWidgets Qt6::Svg Qt6::SvgWidgets)
 	endif()
 	target_include_directories(3rdparty_qt6 INTERFACE ${Qt6Gui_PRIVATE_INCLUDE_DIRS})
 endif()

```

**Comment by engdyn** [comment]
I installed openSUSE Tumbleweed in a VM and had no issues compiling it with my changes. What's the error you're encountering? @regularhunter

**Comment by regularhunter** [comment]
> I installed openSUSE Tumbleweed in a VM and had no issues compiling it with my changes. What's the error you're encountering? @regularhunter

Second attempt built fine on [OBS](https://build.opensuse.org/package/show/home:regularhunter:branches:Emulators/rpcs3). I recreated the test OBS repo from my first attempt after deleting it, there must have had a typo or something in the patch file. I have attached the build log.

[_log.txt](https://github.com/user-attachments/files/22955474/_log.txt)
