### ISSUE TITLE
Compilation failure using gcc 10.2

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#9034]
```
rpcs3/Emu/Cell/Modules/cellSpurs.cpp:1061:98: warning: comparison between ‘enum CellError’ and ‘enum CellNotAnError’ [-Wenum-compare]
 1061 |  if (process_is_spu_lock_line_reservation_address(spurs.addr(), SYS_MEMORY_ACCESS_RIGHT_SPU_THR) != CELL_OK)
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
rpcs3/Emu/Cell/Modules/cellSpurs.cpp:1061:98: error: comparison between types ‘CellError’ and ‘CellNotAnError’ [-Werror=sign-compare]
cc1plus: some warnings being treated as errors
```
Caused by https://github.com/RPCS3/rpcs3/pull/9030
CC @elad335
